<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\urbanizacion;

class urbanizacionseeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $urb = [
            ['id' => 1, 'nombre_urbanizacion' => '28 DE ABRIL', 'Nrodistrito' => 8],
            ['id' => 2, 'nombre_urbanizacion' => 'NUEVA JERUSALEN', 'Nrodistrito' => 8],
            ['id' => 3, 'nombre_urbanizacion' => 'PRIMAVERA II', 'Nrodistrito' => 8],
            ['id' => 4, 'nombre_urbanizacion' => 'APOSTOL SANTIAGO', 'Nrodistrito' => 8],
            ['id' => 5, 'nombre_urbanizacion' => 'CARRION', 'Nrodistrito' => 8],
            ['id' => 6, 'nombre_urbanizacion' => 'LOTEO EBENEZER I', 'Nrodistrito' => 8],
            ['id' => 7, 'nombre_urbanizacion' => 'MAX FERNANDEZ', 'Nrodistrito' => 8],
            ['id' => 8, 'nombre_urbanizacion' => 'CHAYANTA', 'Nrodistrito' => 8],
            ['id' => 9, 'nombre_urbanizacion' => 'LOTEO VENTILLA 2DO', 'Nrodistrito' => 8],
            ['id' => 10, 'nombre_urbanizacion' => 'VILLA ALEJANDRA', 'Nrodistrito' => 8],
            ['id' => 11, 'nombre_urbanizacion' => 'SAN MARTIN B', 'Nrodistrito' => 12],
            ['id' => 12, 'nombre_urbanizacion' => 'LOTEAMIENTO ÑACAHUI PAMPA', 'Nrodistrito' => 8],
            ['id' => 13, 'nombre_urbanizacion' => 'SEÑOR DE VENTILLA', 'Nrodistrito' => 8],
            ['id' => 14, 'nombre_urbanizacion' => 'CRISTAL III', 'Nrodistrito' => 8],
            ['id' => 15, 'nombre_urbanizacion' => 'LOTEO ANEXO URKUPIÑA III', 'Nrodistrito' => 8],
            ['id' => 16, 'nombre_urbanizacion' => 'VIDA ETERNA', 'Nrodistrito' => 8],
            ['id' => 17, 'nombre_urbanizacion' => 'ALAMOS', 'Nrodistrito' => 8],
            ['id' => 18, 'nombre_urbanizacion' => 'LOTEO ANEXO POTOSI', 'Nrodistrito' => 8],
            ['id' => 19, 'nombre_urbanizacion' => 'LOTEO ANEXO 2 SENKATA 79', 'Nrodistrito' => 8],
            ['id' => 20, 'nombre_urbanizacion' => 'LOTEO EBENEZER II', 'Nrodistrito' => 8],
            ['id' => 21, 'nombre_urbanizacion' => 'ROSARIO CENTRAL', 'Nrodistrito' => 8],
            ['id' => 22, 'nombre_urbanizacion' => 'LISBOA', 'Nrodistrito' => 8],
            ['id' => 23, 'nombre_urbanizacion' => 'TRINIDAD GRAN PODER', 'Nrodistrito' => 8],
            ['id' => 24, 'nombre_urbanizacion' => 'COMPLEMENTO FABRIL JUNTUHUMA', 'Nrodistrito' => 8],
            ['id' => 25, 'nombre_urbanizacion' => 'COPACABANA SECTOR VI Y VII 15 DE AGOSTO', 'Nrodistrito' => 8],
            ['id' => 26, 'nombre_urbanizacion' => 'ANTOFAGASTA MANAZANA K', 'Nrodistrito' => 8],
            ['id' => 27, 'nombre_urbanizacion' => 'LOTEO CENTRAL CUMANA', 'Nrodistrito' => 7],
            ['id' => 28, 'nombre_urbanizacion' => 'AGRAMONT', 'Nrodistrito' => 8],
            ['id' => 29, 'nombre_urbanizacion' => 'TARAPACA \"A\" SECTOR NORTE', 'Nrodistrito' => 8],
            ['id' => 30, 'nombre_urbanizacion' => 'ANEXO LEON', 'Nrodistrito' => 7],
            ['id' => 31, 'nombre_urbanizacion' => 'CAMPO VERDE', 'Nrodistrito' => 7],
            ['id' => 32, 'nombre_urbanizacion' => 'LOTEO LOS ANGELES', 'Nrodistrito' => 7],
            ['id' => 33, 'nombre_urbanizacion' => '6 DE SEPTIEMBRE', 'Nrodistrito' => 7],
            ['id' => 34, 'nombre_urbanizacion' => 'ANEXO TOPATER', 'Nrodistrito' => 7],
            ['id' => 35, 'nombre_urbanizacion' => 'NORUEGA', 'Nrodistrito' => 7],
            ['id' => 36, 'nombre_urbanizacion' => 'PLAYA VERDE', 'Nrodistrito' => 7],
            ['id' => 37, 'nombre_urbanizacion' => 'LOTEO LOS ROSALES', 'Nrodistrito' => 7],
            ['id' => 38, 'nombre_urbanizacion' => 'SEÑOR DE MAYO II U.V-\"B\"', 'Nrodistrito' => 7],
            ['id' => 39, 'nombre_urbanizacion' => 'LOTEO 21 DE OCTUBRE \"B\"', 'Nrodistrito' => 7],
            ['id' => 40, 'nombre_urbanizacion' => 'SANTA FE 2', 'Nrodistrito' => 7],
            ['id' => 41, 'nombre_urbanizacion' => 'SAN BENITO', 'Nrodistrito' => 7],
            ['id' => 42, 'nombre_urbanizacion' => '31 DE ENERO', 'Nrodistrito' => 7],
            ['id' => 43, 'nombre_urbanizacion' => 'SAN MIGUEL', 'Nrodistrito' => 7],
            ['id' => 44, 'nombre_urbanizacion' => 'EDUARDO AVAROA CALLIPAMPA', 'Nrodistrito' => 2],
            ['id' => 45, 'nombre_urbanizacion' => 'LOTEO COMPLEMENTO LAS RETAMAS', 'Nrodistrito' => 14],
            ['id' => 46, 'nombre_urbanizacion' => 'VILLA MARCELINA', 'Nrodistrito' => 3],
            ['id' => 47, 'nombre_urbanizacion' => 'ALTO LIMA 4TA SECCION', 'Nrodistrito' => 6],
            ['id' => 48, 'nombre_urbanizacion' => 'ANEXO INGAVI PAMPA', 'Nrodistrito' => 3],
            ['id' => 49, 'nombre_urbanizacion' => 'LOTEO LAURA', 'Nrodistrito' => 14],
            ['id' => 50, 'nombre_urbanizacion' => 'LOTEO SAPECHO', 'Nrodistrito' => 8],
            ['id' => 51, 'nombre_urbanizacion' => 'TURRINI', 'Nrodistrito' => 14],
            ['id' => 52, 'nombre_urbanizacion' => 'LOTEO  WALATA', 'Nrodistrito' => 14],
            ['id' => 53, 'nombre_urbanizacion' => 'VIRGEN DE BETHANIA', 'Nrodistrito' => 10],
            ['id' => 54, 'nombre_urbanizacion' => 'JESUS DE NAZARETH', 'Nrodistrito' => 10],
            ['id' => 55, 'nombre_urbanizacion' => 'SANTA FE ACHICALA', 'Nrodistrito' => 10],
            ['id' => 56, 'nombre_urbanizacion' => 'KORY', 'Nrodistrito' => 7],
            ['id' => 57, 'nombre_urbanizacion' => '14 DE SEPTIEMBRE AMPLIACION I', 'Nrodistrito' => 12],
            ['id' => 58, 'nombre_urbanizacion' => '8 DE ENERO', 'Nrodistrito' => 8],
            ['id' => 59, 'nombre_urbanizacion' => '14 DE SEPTIEMBRE - B', 'Nrodistrito' => 8],
            ['id' => 60, 'nombre_urbanizacion' => 'OLIVOS', 'Nrodistrito' => 8],
            ['id' => 61, 'nombre_urbanizacion' => 'LOTEO HERMANOS VISCARRA', 'Nrodistrito' => 8],
            ['id' => 62, 'nombre_urbanizacion' => 'SAN CARLOS', 'Nrodistrito' => 8],
            ['id' => 63, 'nombre_urbanizacion' => 'EL PARAISO I', 'Nrodistrito' => 8],
            ['id' => 64, 'nombre_urbanizacion' => 'SEÑOR DE MAYO I', 'Nrodistrito' => 8],
            ['id' => 65, 'nombre_urbanizacion' => 'EL PARAISO II', 'Nrodistrito' => 8],
            ['id' => 66, 'nombre_urbanizacion' => 'LOTEO ANEXO SENKATA PUCARANI', 'Nrodistrito' => 8],
            ['id' => 67, 'nombre_urbanizacion' => 'LOTEO EX COMUNIDAD PUCARANI SECTOR CALLIPAMPA', 'Nrodistrito' => 8],
            ['id' => 68, 'nombre_urbanizacion' => 'SOL NACIENTE', 'Nrodistrito' => 8],
            ['id' => 69, 'nombre_urbanizacion' => 'LOTEO ANEXO GENERAL PANDO II', 'Nrodistrito' => 8],
            ['id' => 70, 'nombre_urbanizacion' => '14 DE SEPTIEMBRE VENTILLA', 'Nrodistrito' => 8],
            ['id' => 71, 'nombre_urbanizacion' => 'UNION PUCARANI SENKATA', 'Nrodistrito' => 8],
            ['id' => 72, 'nombre_urbanizacion' => '15 DE AGOSTO', 'Nrodistrito' => 7],
            ['id' => 73, 'nombre_urbanizacion' => 'CHIJINI ALTO', 'Nrodistrito' => 12],
            ['id' => 74, 'nombre_urbanizacion' => 'LOTEO ANEXO RETAMAS', 'Nrodistrito' => 14],
            ['id' => 75, 'nombre_urbanizacion' => 'EL PALMAR', 'Nrodistrito' => 14],
            ['id' => 76, 'nombre_urbanizacion' => 'COPACABANA 18 DE MAYO', 'Nrodistrito' => 8],
            ['id' => 77, 'nombre_urbanizacion' => 'ALTO LIMA 2DA SECCION', 'Nrodistrito' => 6],
            ['id' => 78, 'nombre_urbanizacion' => 'SAN JOSE', 'Nrodistrito' => 14],
            ['id' => 79, 'nombre_urbanizacion' => '31 DE AGOSTO', 'Nrodistrito' => 14],
            ['id' => 80, 'nombre_urbanizacion' => 'BAUTISTA SAAVEDRA U.V. \"F\" MZNO 26,27,46,47', 'Nrodistrito' => 14],
            ['id' => 83, 'nombre_urbanizacion' => 'BAUTISTA SAAVEDRA U.V.\"F\"', 'Nrodistrito' => 14],
            ['id' => 84, 'nombre_urbanizacion' => 'CENTRAL VILLA DOLORES MANZANO \"O\"', 'Nrodistrito' => 1],
            ['id' => 85, 'nombre_urbanizacion' => 'VILLA EXALTACION 3RA SECCION', 'Nrodistrito' => 1],
            ['id' => 86, 'nombre_urbanizacion' => 'VILLA EXALTACION 3RA SECCION MANZANO \"LL\"', 'Nrodistrito' => 1],
            ['id' => 87, 'nombre_urbanizacion' => 'LOTEO VILLA DOLORES MANZANA 403', 'Nrodistrito' => 1],
            ['id' => 88, 'nombre_urbanizacion' => 'LOTEO ROSAS PAMPA  EX FUNDO CUTUTO', 'Nrodistrito' => 1],
            ['id' => 89, 'nombre_urbanizacion' => 'ANEXO CUPILUPACA', 'Nrodistrito' => 2],
            ['id' => 90, 'nombre_urbanizacion' => 'LOTEO VILLA LUISA MZNA I-I1', 'Nrodistrito' => 2],
            ['id' => 92, 'nombre_urbanizacion' => 'SANTO DOMINGO', 'Nrodistrito' => 12],
            ['id' => 93, 'nombre_urbanizacion' => 'LOTEO ASUNCION SAN PEDRO MANZANA 1045', 'Nrodistrito' => 2],
            ['id' => 94, 'nombre_urbanizacion' => 'VILLA ASUNCION SAN PEDRO', 'Nrodistrito' => 2],
            ['id' => 95, 'nombre_urbanizacion' => 'COMPLEMENTO CUPILUPACA', 'Nrodistrito' => 2],
            ['id' => 97, 'nombre_urbanizacion' => 'VILLA BOLIVAR \"D\" MZNO 137', 'Nrodistrito' => 2],
            ['id' => 98, 'nombre_urbanizacion' => 'LOTEO CHARAPAQUI MZNO \"B\"', 'Nrodistrito' => 3],
            ['id' => 99, 'nombre_urbanizacion' => 'ELIODORO CAMACHO', 'Nrodistrito' => 3],
            ['id' => 100, 'nombre_urbanizacion' => 'SAN FELIPE', 'Nrodistrito' => 1],
            ['id' => 101, 'nombre_urbanizacion' => 'HUARICUNCA GRANDE', 'Nrodistrito' => 1],
            ['id' => 102, 'nombre_urbanizacion' => 'VILLA VICTORIA', 'Nrodistrito' => 1],
            ['id' => 103, 'nombre_urbanizacion' => 'LOTEO ALTO DE LA ALIANZA MZNO \"Y2\"', 'Nrodistrito' => 3],
            ['id' => 104, 'nombre_urbanizacion' => 'SAN PEDRO LAJA', 'Nrodistrito' => 12],
            ['id' => 105, 'nombre_urbanizacion' => 'SAN JOSE DE INGAVI', 'Nrodistrito' => 3],
            ['id' => 106, 'nombre_urbanizacion' => 'EL PARAISO MZNO \"M\"', 'Nrodistrito' => 3],
            ['id' => 107, 'nombre_urbanizacion' => 'INTI MANZANO \"B\"', 'Nrodistrito' => 3],
            ['id' => 108, 'nombre_urbanizacion' => 'CHARAPAQUI ANEXO BARRIO LINDO', 'Nrodistrito' => 3],
            ['id' => 109, 'nombre_urbanizacion' => 'VILLA DOLORES F SECTOR FRANZ TAMAYO MZNO \"G\"', 'Nrodistrito' => 3],
            ['id' => 110, 'nombre_urbanizacion' => 'PUERTO RICO', 'Nrodistrito' => 3],
            ['id' => 111, 'nombre_urbanizacion' => 'VILLA PACAJES MZNO \"LL\"', 'Nrodistrito' => 3],
            ['id' => 112, 'nombre_urbanizacion' => 'JAIME PAZ ZAMORA', 'Nrodistrito' => 3],
            ['id' => 113, 'nombre_urbanizacion' => 'VILLA ESTHER MZNO \"B\"', 'Nrodistrito' => 3],
            ['id' => 114, 'nombre_urbanizacion' => 'JARDIN DEL SUR MZNO \"A\"', 'Nrodistrito' => 3],
            ['id' => 115, 'nombre_urbanizacion' => 'CALAMA', 'Nrodistrito' => 3],
            ['id' => 116, 'nombre_urbanizacion' => 'VILLA TUNARI MZNO 118', 'Nrodistrito' => 4],
            ['id' => 117, 'nombre_urbanizacion' => 'VILLA TUNARI MZNO \"67\"', 'Nrodistrito' => 4],
            ['id' => 118, 'nombre_urbanizacion' => 'EX COOPERATIVA VELEROS \"MINA CHOJLLA\"', 'Nrodistrito' => 4],
            ['id' => 119, 'nombre_urbanizacion' => 'VILLA INGAVI SECTOR 14 DE SEPTIEMBRE MZNO \"O\"', 'Nrodistrito' => 5],
            ['id' => 120, 'nombre_urbanizacion' => 'APOLO', 'Nrodistrito' => 14],
            ['id' => 121, 'nombre_urbanizacion' => 'EX COMUNIDAD YUNGUYO MZNA 34-A', 'Nrodistrito' => 4],
            ['id' => 122, 'nombre_urbanizacion' => 'RIO SECO YUNGUYO', 'Nrodistrito' => 4],
            ['id' => 123, 'nombre_urbanizacion' => 'LOTEO JUAN PABLO II', 'Nrodistrito' => 6],
            ['id' => 124, 'nombre_urbanizacion' => 'LOTEO LOS ANDES', 'Nrodistrito' => 7],
            ['id' => 126, 'nombre_urbanizacion' => 'LOTEO SECTOR MARIA AUXILIADORA', 'Nrodistrito' => 5],
            ['id' => 127, 'nombre_urbanizacion' => 'ROSALINDA', 'Nrodistrito' => 14],
            ['id' => 128, 'nombre_urbanizacion' => 'LOTEO HICHUSIRCA GRANDE', 'Nrodistrito' => 7],
            ['id' => 129, 'nombre_urbanizacion' => 'SAN CARLOS V', 'Nrodistrito' => 14],
            ['id' => 131, 'nombre_urbanizacion' => 'SAN CRISPIN', 'Nrodistrito' => 7],
            ['id' => 132, 'nombre_urbanizacion' => 'SANTO TOMAS', 'Nrodistrito' => 14],
            ['id' => 133, 'nombre_urbanizacion' => 'VILLA LAGUNAS', 'Nrodistrito' => 7],
            ['id' => 134, 'nombre_urbanizacion' => 'PEREZ VALENCIA', 'Nrodistrito' => 14],
            ['id' => 135, 'nombre_urbanizacion' => 'LOTEO 25 DE JULIO', 'Nrodistrito' => 7],
            ['id' => 136, 'nombre_urbanizacion' => 'LOTEO 16 DE AGOSTO SAN ROQUE DVISION Y PARTICION', 'Nrodistrito' => 7],
            ['id' => 137, 'nombre_urbanizacion' => 'FRANZ TAMAYO SECTOR TARACO', 'Nrodistrito' => 14],
            ['id' => 138, 'nombre_urbanizacion' => 'CRISTO VENCEDOR', 'Nrodistrito' => 14],
            ['id' => 139, 'nombre_urbanizacion' => 'FRANCO VALLE', 'Nrodistrito' => 14],
            ['id' => 140, 'nombre_urbanizacion' => 'ISRAEL FUSION', 'Nrodistrito' => 7],
            ['id' => 141, 'nombre_urbanizacion' => 'LOTEO SAN ALBERTO PRIMERO', 'Nrodistrito' => 7],
            ['id' => 142, 'nombre_urbanizacion' => 'LOTEO ANEXO BELLA VISTA SUR', 'Nrodistrito' => 7],
            ['id' => 143, 'nombre_urbanizacion' => 'LOS LIRIOS', 'Nrodistrito' => 7],
            ['id' => 144, 'nombre_urbanizacion' => '15 DE FEBRERO', 'Nrodistrito' => 7],
            ['id' => 145, 'nombre_urbanizacion' => 'MIRADOR DE LOS ANDES', 'Nrodistrito' => 7],
            ['id' => 146, 'nombre_urbanizacion' => 'KALAMARCA', 'Nrodistrito' => 8],
            ['id' => 147, 'nombre_urbanizacion' => '8 DE SEPTIEMBRE', 'Nrodistrito' => 5],
            ['id' => 148, 'nombre_urbanizacion' => 'GERMAN BUCH 1-1-2 3RA SEC.', 'Nrodistrito' => 5],
            ['id' => 149, 'nombre_urbanizacion' => 'INTEGRACION', 'Nrodistrito' => 5],
            ['id' => 150, 'nombre_urbanizacion' => 'ANEXO MERCURIO', 'Nrodistrito' => 5],
            ['id' => 151, 'nombre_urbanizacion' => 'MARISCAL SUCRE MILLUNI BAJO SECTOR \"A\"', 'Nrodistrito' => 5],
            ['id' => 152, 'nombre_urbanizacion' => 'LOTEAMIENTO MARISCAL SUCRE', 'Nrodistrito' => 5],
            ['id' => 153, 'nombre_urbanizacion' => 'MARISCAL SUCRE', 'Nrodistrito' => 5],
            ['id' => 154, 'nombre_urbanizacion' => 'HUAYNA POTOSI 1ra. SECCION', 'Nrodistrito' => 5],
            ['id' => 155, 'nombre_urbanizacion' => 'HUAYNA POTOSI 2da. SECCION', 'Nrodistrito' => 5],
            ['id' => 156, 'nombre_urbanizacion' => 'HUAYNA POTOSI 3ra.SECCION', 'Nrodistrito' => 5],
            ['id' => 157, 'nombre_urbanizacion' => 'VILLA TUPCAC KATARI', 'Nrodistrito' => 5],
            ['id' => 158, 'nombre_urbanizacion' => 'MERCURIO', 'Nrodistrito' => 5],
            ['id' => 161, 'nombre_urbanizacion' => 'MERCURIO PLAN 400', 'Nrodistrito' => 5],
            ['id' => 162, 'nombre_urbanizacion' => 'VILLA INGAVI', 'Nrodistrito' => 5],
            ['id' => 163, 'nombre_urbanizacion' => 'VILLA REMEDIOS - INGENIO', 'Nrodistrito' => 5],
            ['id' => 164, 'nombre_urbanizacion' => 'COMPLEMENTO GERMAN BUSCH DISTRITO 1-1-2', 'Nrodistrito' => 5],
            ['id' => 165, 'nombre_urbanizacion' => 'GERMAN BUSCH ANEXO 1-1-2', 'Nrodistrito' => 5],
            ['id' => 166, 'nombre_urbanizacion' => 'SANTA ROSA DE LIMA', 'Nrodistrito' => 5],
            ['id' => 167, 'nombre_urbanizacion' => 'GERMAN BUSCH  OESTE', 'Nrodistrito' => 5],
            ['id' => 168, 'nombre_urbanizacion' => 'VILLA ESPERANZA PLAN VIVIENDA', 'Nrodistrito' => 5],
            ['id' => 169, 'nombre_urbanizacion' => 'COMPLEMENTO MERCURIO', 'Nrodistrito' => 5],
            ['id' => 170, 'nombre_urbanizacion' => 'COMPLEMENTO GRUPO 33 HUAYNA POTOSI', 'Nrodistrito' => 5],
            ['id' => 171, 'nombre_urbanizacion' => 'ATALAYA', 'Nrodistrito' => 5],
            ['id' => 172, 'nombre_urbanizacion' => 'VILLA ESPERANZA', 'Nrodistrito' => 5],
            ['id' => 173, 'nombre_urbanizacion' => 'GERMAN BUSCH DISTRITO 1-1-3', 'Nrodistrito' => 5],
            ['id' => 174, 'nombre_urbanizacion' => 'COMPLEMENTO GERMAN BUSCH DISTRITO 1-1-3', 'Nrodistrito' => 5],
            ['id' => 175, 'nombre_urbanizacion' => 'REY DAVID', 'Nrodistrito' => 5],
            ['id' => 176, 'nombre_urbanizacion' => 'PUERTO MEJILLONES', 'Nrodistrito' => 5],
            ['id' => 177, 'nombre_urbanizacion' => 'ANEXO TAHUANTISUYO', 'Nrodistrito' => 5],
            ['id' => 178, 'nombre_urbanizacion' => 'NUEVA ASUNCION U.V. 1', 'Nrodistrito' => 5],
            ['id' => 179, 'nombre_urbanizacion' => 'NUEVA ASUNCION U.V. 2', 'Nrodistrito' => 5],
            ['id' => 180, 'nombre_urbanizacion' => 'NUEVA ASUNCION U.V. 3', 'Nrodistrito' => 5],
            ['id' => 181, 'nombre_urbanizacion' => 'NUEVA ASUNCION U.V. 4', 'Nrodistrito' => 5],
            ['id' => 182, 'nombre_urbanizacion' => 'LOTEO COMPLEMENTO TIPO 1-1 (RIO SECO)', 'Nrodistrito' => 5],
            ['id' => 183, 'nombre_urbanizacion' => 'VILLA TAHUANTISUYO', 'Nrodistrito' => 5],
            ['id' => 184, 'nombre_urbanizacion' => 'EL INGENIO UNIDAD VECINAL  1', 'Nrodistrito' => 5],
            ['id' => 185, 'nombre_urbanizacion' => 'EL INGENIO DISTRITO  2 UNIDAD 1', 'Nrodistrito' => 5],
            ['id' => 186, 'nombre_urbanizacion' => 'EL INGENIO DISTRITO  1 UNIDAD VECINAL 3', 'Nrodistrito' => 5],
            ['id' => 187, 'nombre_urbanizacion' => 'VILLA LOTEO DE BOLIVAR Y KK', 'Nrodistrito' => 1],
            ['id' => 188, 'nombre_urbanizacion' => 'VILLA DOLORES', 'Nrodistrito' => 1],
            ['id' => 189, 'nombre_urbanizacion' => 'TEJADA TRIANDULAR', 'Nrodistrito' => 1],
            ['id' => 190, 'nombre_urbanizacion' => '12  DE OCTUBRE (BARRIO MINERO)', 'Nrodistrito' => 1],
            ['id' => 191, 'nombre_urbanizacion' => 'LOTEO CHARAPAQUI EL ALTO', 'Nrodistrito' => 3],
            ['id' => 192, 'nombre_urbanizacion' => 'CHARAPAQUI', 'Nrodistrito' => 3],
            ['id' => 193, 'nombre_urbanizacion' => 'EL INGENIO DISTRITO 1N UNIDAD VECINAL  4', 'Nrodistrito' => 5],
            ['id' => 194, 'nombre_urbanizacion' => 'INGENIO DSITRITO 1 UNIDAD VECINAL 2', 'Nrodistrito' => 5],
            ['id' => 195, 'nombre_urbanizacion' => 'EL INGENIO DISTRITO 2 UNIDAD  2 UNIDAD 3', 'Nrodistrito' => 5],
            ['id' => 196, 'nombre_urbanizacion' => 'EL INGENIO DISTRITO 2 UNIDAD 4', 'Nrodistrito' => 5],
            ['id' => 197, 'nombre_urbanizacion' => 'EL INGENIO DISTRITO 2 UNIDAD 2', 'Nrodistrito' => 5],
            ['id' => 198, 'nombre_urbanizacion' => 'LOTEO PANAMERICANA', 'Nrodistrito' => 5],
            ['id' => 199, 'nombre_urbanizacion' => 'LOTEO PANAMERICANA', 'Nrodistrito' => 5],
            ['id' => 200, 'nombre_urbanizacion' => 'GERMAN BUSCH DISTRITO 1-1-2', 'Nrodistrito' => 5],
            ['id' => 201, 'nombre_urbanizacion' => 'SAN FRANCISCO SILVA', 'Nrodistrito' => 5],
            ['id' => 202, 'nombre_urbanizacion' => 'SAN JUAN RIO SECO', 'Nrodistrito' => 5],
            ['id' => 203, 'nombre_urbanizacion' => '3 DE MAYO', 'Nrodistrito' => 5],
            ['id' => 204, 'nombre_urbanizacion' => 'ALTIPLANO', 'Nrodistrito' => 5],
            ['id' => 205, 'nombre_urbanizacion' => 'MARISCAL SUCRE SECTOR  II', 'Nrodistrito' => 5],
            ['id' => 206, 'nombre_urbanizacion' => 'ANEXO HIUAYNA POTOSI', 'Nrodistrito' => 5],
            ['id' => 207, 'nombre_urbanizacion' => 'VILLA ESTHER MANZANO \"A\"', 'Nrodistrito' => 3],
            ['id' => 208, 'nombre_urbanizacion' => 'SAN PEDRO CHARAPAQUI', 'Nrodistrito' => 3],
            ['id' => 209, 'nombre_urbanizacion' => 'VILLA LA AMISTAD', 'Nrodistrito' => 3],
            ['id' => 210, 'nombre_urbanizacion' => 'CRUZ DEL SUR', 'Nrodistrito' => 3],
            ['id' => 211, 'nombre_urbanizacion' => 'AMOR DE DIOS MZNOS 29 Y 30', 'Nrodistrito' => 3],
            ['id' => 212, 'nombre_urbanizacion' => 'COMPLEMENTO EL PARAISO', 'Nrodistrito' => 3],
            ['id' => 213, 'nombre_urbanizacion' => 'LUIS ESPINAL CAMPS', 'Nrodistrito' => 3],
            ['id' => 214, 'nombre_urbanizacion' => 'VILLA ALEMANIA', 'Nrodistrito' => 3],
            ['id' => 215, 'nombre_urbanizacion' => 'CENTRO UNION ACHIRI', 'Nrodistrito' => 3],
            ['id' => 216, 'nombre_urbanizacion' => 'CANDELARIA', 'Nrodistrito' => 3],
            ['id' => 217, 'nombre_urbanizacion' => 'BARTOLINA SISA', 'Nrodistrito' => 3],
            ['id' => 218, 'nombre_urbanizacion' => 'AMIG. CHACO', 'Nrodistrito' => 3],
            ['id' => 219, 'nombre_urbanizacion' => 'EL PARAISO', 'Nrodistrito' => 3],
            ['id' => 220, 'nombre_urbanizacion' => 'CALAMA', 'Nrodistrito' => 3],
            ['id' => 221, 'nombre_urbanizacion' => 'BARRIO MADRID', 'Nrodistrito' => 3],
            ['id' => 222, 'nombre_urbanizacion' => 'YUNGUYO MOJON VILLA ADELA-COLLPANI', 'Nrodistrito' => 3],
            ['id' => 223, 'nombre_urbanizacion' => 'DEL RIO CHOQUEHUANCA', 'Nrodistrito' => 3],
            ['id' => 224, 'nombre_urbanizacion' => 'JARDIN', 'Nrodistrito' => 3],
            ['id' => 225, 'nombre_urbanizacion' => '10 DE FEBRERO', 'Nrodistrito' => 3],
            ['id' => 226, 'nombre_urbanizacion' => 'COSMOS 79 UV \"C\"', 'Nrodistrito' => 3],
            ['id' => 227, 'nombre_urbanizacion' => 'COSMOS 79 UV \"H\"', 'Nrodistrito' => 3],
            ['id' => 228, 'nombre_urbanizacion' => 'JUAN PABLO II', 'Nrodistrito' => 3],
            ['id' => 229, 'nombre_urbanizacion' => 'COSMOS 79 UV \"E\"', 'Nrodistrito' => 3],
            ['id' => 230, 'nombre_urbanizacion' => 'COSMOS 79 UV \"F\"', 'Nrodistrito' => 3],
            ['id' => 231, 'nombre_urbanizacion' => 'COSMOS 79 UV \"G\"', 'Nrodistrito' => 3],
            ['id' => 232, 'nombre_urbanizacion' => 'COSMOS 79 UV \"D\"', 'Nrodistrito' => 3],
            ['id' => 233, 'nombre_urbanizacion' => 'VILLA ADELA', 'Nrodistrito' => 3],
            ['id' => 234, 'nombre_urbanizacion' => 'SANTA ANA', 'Nrodistrito' => 3],
            ['id' => 235, 'nombre_urbanizacion' => 'COSMOS 79 UV \"A\"', 'Nrodistrito' => 3],
            ['id' => 236, 'nombre_urbanizacion' => 'VILLA BOLIVAR \"C\"', 'Nrodistrito' => 3],
            ['id' => 237, 'nombre_urbanizacion' => 'VILLA DOLORES \"F\"', 'Nrodistrito' => 3],
            ['id' => 238, 'nombre_urbanizacion' => 'ALTO DE ALIANZA', 'Nrodistrito' => 3],
            ['id' => 239, 'nombre_urbanizacion' => 'EL SALVADOR', 'Nrodistrito' => 3],
            ['id' => 240, 'nombre_urbanizacion' => 'LOS POCITOS', 'Nrodistrito' => 3],
            ['id' => 241, 'nombre_urbanizacion' => 'ANEXO INGAVI PAMPA', 'Nrodistrito' => 3],
            ['id' => 242, 'nombre_urbanizacion' => 'INGAVI PAMPA', 'Nrodistrito' => 3],
            ['id' => 243, 'nombre_urbanizacion' => 'SAJAMA', 'Nrodistrito' => 3],
            ['id' => 244, 'nombre_urbanizacion' => '3 DE MAYO', 'Nrodistrito' => 3],
            ['id' => 245, 'nombre_urbanizacion' => 'MURURATA', 'Nrodistrito' => 3],
            ['id' => 246, 'nombre_urbanizacion' => 'CHARAPAQUI I', 'Nrodistrito' => 3],
            ['id' => 247, 'nombre_urbanizacion' => 'MUNICIPAL', 'Nrodistrito' => 3],
            ['id' => 248, 'nombre_urbanizacion' => 'VILLA ROMERO PAMPA', 'Nrodistrito' => 3],
            ['id' => 249, 'nombre_urbanizacion' => 'MIGUELITO', 'Nrodistrito' => 3],
            ['id' => 250, 'nombre_urbanizacion' => 'VILLA JULIANA', 'Nrodistrito' => 3],
            ['id' => 251, 'nombre_urbanizacion' => '24 DE JUNIO', 'Nrodistrito' => 3],
            ['id' => 252, 'nombre_urbanizacion' => 'SAN LUIS 1RO DE MAYO', 'Nrodistrito' => 3],
            ['id' => 253, 'nombre_urbanizacion' => 'SAN NICOLAS', 'Nrodistrito' => 3],
            ['id' => 254, 'nombre_urbanizacion' => 'SAN LUIS II CHARAPAQUI', 'Nrodistrito' => 3],
            ['id' => 255, 'nombre_urbanizacion' => 'CESAR AUGUSTO', 'Nrodistrito' => 3],
            ['id' => 256, 'nombre_urbanizacion' => 'VILLA ILLAMPU', 'Nrodistrito' => 3],
            ['id' => 257, 'nombre_urbanizacion' => 'SAN JOSE DE CHARAQUI II', 'Nrodistrito' => 3],
            ['id' => 258, 'nombre_urbanizacion' => 'NATIVIDAD', 'Nrodistrito' => 3],
            ['id' => 259, 'nombre_urbanizacion' => 'SAN EUGENIO', 'Nrodistrito' => 3],
            ['id' => 260, 'nombre_urbanizacion' => 'LOZA SECTOR CHALLA KOTA', 'Nrodistrito' => 3],
            ['id' => 261, 'nombre_urbanizacion' => 'LAS ROSAS', 'Nrodistrito' => 3],
            ['id' => 262, 'nombre_urbanizacion' => 'JESUS DE NAZARETH', 'Nrodistrito' => 3],
            ['id' => 263, 'nombre_urbanizacion' => 'VILLA MARCELINA', 'Nrodistrito' => 3],
            ['id' => 264, 'nombre_urbanizacion' => 'COSMOS 77', 'Nrodistrito' => 3],
            ['id' => 265, 'nombre_urbanizacion' => 'ANTOFAGASTA', 'Nrodistrito' => 3],
            ['id' => 266, 'nombre_urbanizacion' => 'SAN JUAN 24 JUNIO', 'Nrodistrito' => 3],
            ['id' => 267, 'nombre_urbanizacion' => 'SONATEX', 'Nrodistrito' => 3],
            ['id' => 268, 'nombre_urbanizacion' => '1RO DE MAYO', 'Nrodistrito' => 3],
            ['id' => 269, 'nombre_urbanizacion' => 'NUEVA JERUSALEM', 'Nrodistrito' => 3],
            ['id' => 270, 'nombre_urbanizacion' => 'EX CHARAPAQUI-MURURATA', 'Nrodistrito' => 3],
            ['id' => 271, 'nombre_urbanizacion' => 'LOS PINOS', 'Nrodistrito' => 3],
            ['id' => 272, 'nombre_urbanizacion' => 'SANTA LUCIA', 'Nrodistrito' => 3],
            ['id' => 273, 'nombre_urbanizacion' => '2 DE ABRIL', 'Nrodistrito' => 3],
            ['id' => 274, 'nombre_urbanizacion' => 'LOZA CHARAPAQUI', 'Nrodistrito' => 3],
            ['id' => 275, 'nombre_urbanizacion' => 'COMPLEMENTO SAN LUIS TASA', 'Nrodistrito' => 3],
            ['id' => 276, 'nombre_urbanizacion' => 'SAN LUIS TASA', 'Nrodistrito' => 3],
            ['id' => 277, 'nombre_urbanizacion' => 'LAS QUISWARAS', 'Nrodistrito' => 3],
            ['id' => 278, 'nombre_urbanizacion' => 'CHARAPAQUI II', 'Nrodistrito' => 3],
            ['id' => 279, 'nombre_urbanizacion' => 'COSMOS 78', 'Nrodistrito' => 3],
            ['id' => 280, 'nombre_urbanizacion' => 'VILLA PRIMAVERA', 'Nrodistrito' => 3],
            ['id' => 281, 'nombre_urbanizacion' => 'SAN AGUSTIN', 'Nrodistrito' => 3],
            ['id' => 282, 'nombre_urbanizacion' => '24 DE DICIEMBRE', 'Nrodistrito' => 3],
            ['id' => 283, 'nombre_urbanizacion' => 'SAN LUIS PAMPA', 'Nrodistrito' => 3],
            ['id' => 284, 'nombre_urbanizacion' => 'LOS SAUCES', 'Nrodistrito' => 3],
            ['id' => 285, 'nombre_urbanizacion' => 'ZONA FRANCA LA PAZ', 'Nrodistrito' => 3],
            ['id' => 286, 'nombre_urbanizacion' => 'BARRIO DEL PERIODISTA JESUS OBRERO', 'Nrodistrito' => 3],
            ['id' => 287, 'nombre_urbanizacion' => 'CAFETALEROS YUNGUEÑOS (AMPROCA)', 'Nrodistrito' => 3],
            ['id' => 288, 'nombre_urbanizacion' => 'SAN LUIS ZONGO', 'Nrodistrito' => 3],
            ['id' => 289, 'nombre_urbanizacion' => 'INTI', 'Nrodistrito' => 3],
            ['id' => 290, 'nombre_urbanizacion' => 'COMPLEMENTO 6 DE JUNIO', 'Nrodistrito' => 3],
            ['id' => 291, 'nombre_urbanizacion' => '7 DE SEPTIEMBRE', 'Nrodistrito' => 3],
            ['id' => 292, 'nombre_urbanizacion' => 'ANEXO 7 DE SEPTIEMBRE', 'Nrodistrito' => 3],
            ['id' => 293, 'nombre_urbanizacion' => 'VILLA CALUYO', 'Nrodistrito' => 3],
            ['id' => 294, 'nombre_urbanizacion' => 'VILLA BOLIVAR \"F\"', 'Nrodistrito' => 3],
            ['id' => 295, 'nombre_urbanizacion' => 'VILLA DOLORES \"F\" SECTOR FRANZ TAMAYO', 'Nrodistrito' => 3],
            ['id' => 296, 'nombre_urbanizacion' => 'LA PRIMERA', 'Nrodistrito' => 3],
            ['id' => 297, 'nombre_urbanizacion' => 'ANEXO ALTO DE LA ALIANZA COLLPANI', 'Nrodistrito' => 3],
            ['id' => 298, 'nombre_urbanizacion' => 'VILLA PACAJES', 'Nrodistrito' => 3],
            ['id' => 299, 'nombre_urbanizacion' => 'ILLIMANI', 'Nrodistrito' => 3],
            ['id' => 300, 'nombre_urbanizacion' => 'SAN JOSE DE CHARAPAQUI I', 'Nrodistrito' => 3],
            ['id' => 301, 'nombre_urbanizacion' => 'SAN PABLO', 'Nrodistrito' => 3],
            ['id' => 302, 'nombre_urbanizacion' => 'LOZA VASCAL', 'Nrodistrito' => 3],
            ['id' => 303, 'nombre_urbanizacion' => 'LOTEO ALTO DE LA ALIANZA', 'Nrodistrito' => 3],
            ['id' => 304, 'nombre_urbanizacion' => 'ELIODORO CAMACHO 1RA SECCION', 'Nrodistrito' => 3],
            ['id' => 305, 'nombre_urbanizacion' => 'COMPLEMENTO JESUS DE NAZARETH', 'Nrodistrito' => 3],
            ['id' => 306, 'nombre_urbanizacion' => '1RO DE MARZO', 'Nrodistrito' => 3],
            ['id' => 307, 'nombre_urbanizacion' => 'ANEXO NATIVIDAD', 'Nrodistrito' => 3],
            ['id' => 308, 'nombre_urbanizacion' => 'COMPLEMENTO NATIVIDAD', 'Nrodistrito' => 3],
            ['id' => 309, 'nombre_urbanizacion' => 'COMPLEMENTO NATIVIDAD CHARAPAQUI', 'Nrodistrito' => 3],
            ['id' => 310, 'nombre_urbanizacion' => 'LOTEO MURURATA ANEXO', 'Nrodistrito' => 3],
            ['id' => 311, 'nombre_urbanizacion' => 'BARRIO LINDO CARRETERA VIACHA', 'Nrodistrito' => 3],
            ['id' => 312, 'nombre_urbanizacion' => 'CASA HEREDIA', 'Nrodistrito' => 7],
            ['id' => 313, 'nombre_urbanizacion' => 'LOTEO LOS RAMOS', 'Nrodistrito' => 7],
            ['id' => 314, 'nombre_urbanizacion' => 'SAN JUAN I', 'Nrodistrito' => 7],
            ['id' => 315, 'nombre_urbanizacion' => 'SOL NACIENTE', 'Nrodistrito' => 7],
            ['id' => 316, 'nombre_urbanizacion' => '15 DE AGOSTO', 'Nrodistrito' => 7],
            ['id' => 317, 'nombre_urbanizacion' => 'LOS PINOS', 'Nrodistrito' => 7],
            ['id' => 318, 'nombre_urbanizacion' => 'MARIA DE URKUPIÑA', 'Nrodistrito' => 7],
            ['id' => 319, 'nombre_urbanizacion' => 'VILLA ANDRANI', 'Nrodistrito' => 7],
            ['id' => 320, 'nombre_urbanizacion' => 'EL ROSARIO', 'Nrodistrito' => 7],
            ['id' => 321, 'nombre_urbanizacion' => 'LOTEO SAN FRANCISCO', 'Nrodistrito' => 7],
            ['id' => 322, 'nombre_urbanizacion' => 'SAN ROQUE 16 DE AGOSTO', 'Nrodistrito' => 7],
            ['id' => 323, 'nombre_urbanizacion' => 'PRADOS DEL NORTE SAN ROQUE', 'Nrodistrito' => 7],
            ['id' => 324, 'nombre_urbanizacion' => 'UNIFICADA', 'Nrodistrito' => 7],
            ['id' => 325, 'nombre_urbanizacion' => 'TOPATER', 'Nrodistrito' => 7],
            ['id' => 326, 'nombre_urbanizacion' => 'EL PORVENIR II', 'Nrodistrito' => 7],
            ['id' => 327, 'nombre_urbanizacion' => '6 DE MARZO', 'Nrodistrito' => 7],
            ['id' => 328, 'nombre_urbanizacion' => 'SEÑOR DE LAGUNAS 2000', 'Nrodistrito' => 7],
            ['id' => 329, 'nombre_urbanizacion' => 'VILLA MERCEDES U.V. \"E\"', 'Nrodistrito' => 8],
            ['id' => 330, 'nombre_urbanizacion' => 'VILLA MERCEDES U.V. \"F\"', 'Nrodistrito' => 8],
            ['id' => 331, 'nombre_urbanizacion' => 'VILLA MERCEDES ANEXO', 'Nrodistrito' => 8],
            ['id' => 332, 'nombre_urbanizacion' => 'VILLA MERCEDES U.V. \"G\"', 'Nrodistrito' => 8],
            ['id' => 333, 'nombre_urbanizacion' => 'VILLA MERCEDES U.V. \"I\"', 'Nrodistrito' => 8],
            ['id' => 334, 'nombre_urbanizacion' => 'VILLA MERCEDES U.V. \"H\"', 'Nrodistrito' => 8],
            ['id' => 335, 'nombre_urbanizacion' => 'VILLA MERCEDES U.V. \"D\"', 'Nrodistrito' => 8],
            ['id' => 336, 'nombre_urbanizacion' => 'NUEVO AMANECER SECTOR MERCEDES', 'Nrodistrito' => 8],
            ['id' => 337, 'nombre_urbanizacion' => 'CUMARAVI', 'Nrodistrito' => 8],
            ['id' => 338, 'nombre_urbanizacion' => 'SAN SILVESTRE', 'Nrodistrito' => 8],
            ['id' => 339, 'nombre_urbanizacion' => 'VILLA KHANTATI', 'Nrodistrito' => 8],
            ['id' => 340, 'nombre_urbanizacion' => 'SAN AGUSTIN', 'Nrodistrito' => 8],
            ['id' => 341, 'nombre_urbanizacion' => 'COPACABANA', 'Nrodistrito' => 8],
            ['id' => 342, 'nombre_urbanizacion' => 'SAN SILVESTRE', 'Nrodistrito' => 8],
            ['id' => 343, 'nombre_urbanizacion' => 'TARAPACA \"C\"', 'Nrodistrito' => 8],
            ['id' => 344, 'nombre_urbanizacion' => 'PRIMAVERA JUNTUHUMA', 'Nrodistrito' => 8],
            ['id' => 345, 'nombre_urbanizacion' => 'LOTEO 27 DE SEPTIEMBRE', 'Nrodistrito' => 8],
            ['id' => 346, 'nombre_urbanizacion' => 'LA SOLUCION', 'Nrodistrito' => 8],
            ['id' => 347, 'nombre_urbanizacion' => 'VENTILLA SEGUNDO', 'Nrodistrito' => 8],
            ['id' => 348, 'nombre_urbanizacion' => 'ANEXO MODELO', 'Nrodistrito' => 8],
            ['id' => 349, 'nombre_urbanizacion' => 'VERA CRUZ', 'Nrodistrito' => 8],
            ['id' => 350, 'nombre_urbanizacion' => 'AMOR DE DIOS', 'Nrodistrito' => 3],
            ['id' => 351, 'nombre_urbanizacion' => 'VILLA ESTHER', 'Nrodistrito' => 3],
            ['id' => 352, 'nombre_urbanizacion' => 'LOTEO JARDIN DEL SUR', 'Nrodistrito' => 3],
            ['id' => 353, 'nombre_urbanizacion' => 'JARDIN DEL SUR', 'Nrodistrito' => 3],
            ['id' => 354, 'nombre_urbanizacion' => 'COMPLEMENTO FRANJA CRUCE VILLA ADELA', 'Nrodistrito' => 3],
            ['id' => 355, 'nombre_urbanizacion' => 'CRUCE CARRETERA VIACHA Y V.ADELA', 'Nrodistrito' => 3],
            ['id' => 356, 'nombre_urbanizacion' => 'COMPLEMENTO FRANZ TAMAYO', 'Nrodistrito' => 3],
            ['id' => 357, 'nombre_urbanizacion' => 'REGIMIENTO POLICIAL Nro 1', 'Nrodistrito' => 3],
            ['id' => 358, 'nombre_urbanizacion' => 'EX COMUNIDAD COLLPANI', 'Nrodistrito' => 3],
            ['id' => 359, 'nombre_urbanizacion' => '25 DE DICIEMBRE', 'Nrodistrito' => 3],
            ['id' => 360, 'nombre_urbanizacion' => 'COMPLEMENTO BARRIO LINDO', 'Nrodistrito' => 3],
            ['id' => 361, 'nombre_urbanizacion' => 'ESTEBAN QUINO', 'Nrodistrito' => 3],
            ['id' => 362, 'nombre_urbanizacion' => '2 DE FEBRERO', 'Nrodistrito' => 3],
            ['id' => 363, 'nombre_urbanizacion' => 'COSMOS 79 UV \"B\"', 'Nrodistrito' => 3],
            ['id' => 364, 'nombre_urbanizacion' => 'FERROVIARIA', 'Nrodistrito' => 6],
            ['id' => 365, 'nombre_urbanizacion' => 'ALTO LIMA 4TA SECCION', 'Nrodistrito' => 6],
            ['id' => 366, 'nombre_urbanizacion' => 'VILLA SANTIAGO I', 'Nrodistrito' => 1],
            ['id' => 367, 'nombre_urbanizacion' => 'COMPLEMETO VILLA INGAVI', 'Nrodistrito' => 5],
            ['id' => 368, 'nombre_urbanizacion' => 'FERROPETROL', 'Nrodistrito' => 6],
            ['id' => 369, 'nombre_urbanizacion' => 'BALLIVIAN 2da SECCION MANZANO 108-A', 'Nrodistrito' => 6],
            ['id' => 370, 'nombre_urbanizacion' => 'ALTO LIMA 3RA SECCION SUD', 'Nrodistrito' => 6],
            ['id' => 371, 'nombre_urbanizacion' => 'ALTO LIMA 1RA SECCION SECTOR MANZANA \"O\"', 'Nrodistrito' => 6],
            ['id' => 372, 'nombre_urbanizacion' => 'OBREROS FERROVIARIO', 'Nrodistrito' => 6],
            ['id' => 373, 'nombre_urbanizacion' => 'ALTO LIMA 3RA SECCION NORTE', 'Nrodistrito' => 6],
            ['id' => 374, 'nombre_urbanizacion' => '16 DE JULIO 2DA SECCION', 'Nrodistrito' => 6],
            ['id' => 375, 'nombre_urbanizacion' => '16 DE JULIO 3RA SECCION', 'Nrodistrito' => 6],
            ['id' => 376, 'nombre_urbanizacion' => 'LOS ANDES', 'Nrodistrito' => 6],
            ['id' => 377, 'nombre_urbanizacion' => '16 DE JULIO 1RA SECCION', 'Nrodistrito' => 6],
            ['id' => 378, 'nombre_urbanizacion' => 'BALLIVIAN 1RA SECCION', 'Nrodistrito' => 6],
            ['id' => 379, 'nombre_urbanizacion' => 'SAID ALTO VILLA VICTORIA', 'Nrodistrito' => 6],
            ['id' => 380, 'nombre_urbanizacion' => 'ALTO LIMA 1RA SECCION', 'Nrodistrito' => 6],
            ['id' => 381, 'nombre_urbanizacion' => 'ALTO LIMA 4TA SECCION', 'Nrodistrito' => 6],
            ['id' => 382, 'nombre_urbanizacion' => 'ALTO LIMA 2DA SECCION', 'Nrodistrito' => 6],
            ['id' => 383, 'nombre_urbanizacion' => 'BALLIVIAN 2DA SECCION', 'Nrodistrito' => 6],
            ['id' => 384, 'nombre_urbanizacion' => 'LOTEO 16 DE JULIO MANZ. 41B, 42B', 'Nrodistrito' => 6],
            ['id' => 385, 'nombre_urbanizacion' => 'ALTO LIMA 1RA SECCIÃ“N SECTOR COMPLEMENTO MANZANA \"O\"', 'Nrodistrito' => 6],
            ['id' => 386, 'nombre_urbanizacion' => '18 DE MAYO', 'Nrodistrito' => 6],
            ['id' => 387, 'nombre_urbanizacion' => 'EL SALVADOR BUSTOS', 'Nrodistrito' => 6],
            ['id' => 388, 'nombre_urbanizacion' => 'ALTO LIMA 3RA SECCION CENTRAL', 'Nrodistrito' => 6],
            ['id' => 389, 'nombre_urbanizacion' => 'ANEXO16 DE JULIO', 'Nrodistrito' => 6],
            ['id' => 390, 'nombre_urbanizacion' => 'ASSANA LORETO', 'Nrodistrito' => 6],
            ['id' => 391, 'nombre_urbanizacion' => 'REY DE REYES', 'Nrodistrito' => 7],
            ['id' => 392, 'nombre_urbanizacion' => 'ANEXO KANTATI', 'Nrodistrito' => 7],
            ['id' => 393, 'nombre_urbanizacion' => '20 DE MAYO', 'Nrodistrito' => 7],
            ['id' => 394, 'nombre_urbanizacion' => 'MORALES', 'Nrodistrito' => 7],
            ['id' => 395, 'nombre_urbanizacion' => 'CRUZ DE LAGUNA', 'Nrodistrito' => 7],
            ['id' => 396, 'nombre_urbanizacion' => 'MAXIMA PEREZ', 'Nrodistrito' => 7],
            ['id' => 397, 'nombre_urbanizacion' => 'LOTEO ANEXO SAN ANTONIO', 'Nrodistrito' => 7],
            ['id' => 398, 'nombre_urbanizacion' => '21 DE OCTUBRE \"A\"', 'Nrodistrito' => 7],
            ['id' => 399, 'nombre_urbanizacion' => 'SARAWI', 'Nrodistrito' => 7],
            ['id' => 400, 'nombre_urbanizacion' => '2 DE AGOSTO', 'Nrodistrito' => 7],
            ['id' => 401, 'nombre_urbanizacion' => 'FERROVIARIA', 'Nrodistrito' => 6],
            ['id' => 402, 'nombre_urbanizacion' => 'LOTEO JULIAN APAZA II', 'Nrodistrito' => 7],
            ['id' => 403, 'nombre_urbanizacion' => 'LOTEO 16 DE AGOSTO', 'Nrodistrito' => 7],
            ['id' => 404, 'nombre_urbanizacion' => 'LOTEO ILAYA', 'Nrodistrito' => 7],
            ['id' => 405, 'nombre_urbanizacion' => 'LOTEO YAPACANI', 'Nrodistrito' => 7],
            ['id' => 406, 'nombre_urbanizacion' => 'SEÑOR DE LAGUNAS NORTE', 'Nrodistrito' => 7],
            ['id' => 407, 'nombre_urbanizacion' => 'NUEVO AMANECER II SAN ROQUE', 'Nrodistrito' => 7],
            ['id' => 408, 'nombre_urbanizacion' => 'LOTEO SAN LUCAS II', 'Nrodistrito' => 7],
            ['id' => 409, 'nombre_urbanizacion' => 'SAN JUAN SAN ROQUE', 'Nrodistrito' => 7],
            ['id' => 410, 'nombre_urbanizacion' => 'ISRAEL', 'Nrodistrito' => 7],
            ['id' => 411, 'nombre_urbanizacion' => 'SAN SIMON', 'Nrodistrito' => 7],
            ['id' => 412, 'nombre_urbanizacion' => 'SAN LUIS DE SAN ROQUE', 'Nrodistrito' => 7],
            ['id' => 413, 'nombre_urbanizacion' => 'JICHUCIRCA', 'Nrodistrito' => 7],
            ['id' => 414, 'nombre_urbanizacion' => 'SAN MARTIN', 'Nrodistrito' => 7],
            ['id' => 415, 'nombre_urbanizacion' => 'VALLE HERMOSO II EX FUNDO SAN ROQUE', 'Nrodistrito' => 7],
            ['id' => 416, 'nombre_urbanizacion' => 'SAN JUAN 24 DE JUNIO', 'Nrodistrito' => 7],
            ['id' => 417, 'nombre_urbanizacion' => 'VIRGEN DE LAS NIEVES', 'Nrodistrito' => 7],
            ['id' => 418, 'nombre_urbanizacion' => 'SAN FRANCISCO', 'Nrodistrito' => 7],
            ['id' => 419, 'nombre_urbanizacion' => 'CUYAURI', 'Nrodistrito' => 7],
            ['id' => 420, 'nombre_urbanizacion' => '5 DE JULIO II', 'Nrodistrito' => 7],
            ['id' => 421, 'nombre_urbanizacion' => 'LOTEO 21 DE OCTUBRE  B', 'Nrodistrito' => 7],
            ['id' => 422, 'nombre_urbanizacion' => 'MARGARITA', 'Nrodistrito' => 7],
            ['id' => 423, 'nombre_urbanizacion' => 'CALA CALA', 'Nrodistrito' => 7],
            ['id' => 424, 'nombre_urbanizacion' => 'NUEVA SANTA CRUZ', 'Nrodistrito' => 7],
            ['id' => 425, 'nombre_urbanizacion' => 'EL SANTUARIO', 'Nrodistrito' => 7],
            ['id' => 426, 'nombre_urbanizacion' => 'LEON', 'Nrodistrito' => 7],
            ['id' => 427, 'nombre_urbanizacion' => 'LOTEO QOLLANA', 'Nrodistrito' => 7],
            ['id' => 428, 'nombre_urbanizacion' => 'SEÑOR DE LAGUNAS 21 DE SEPTIEMBRE', 'Nrodistrito' => 7],
            ['id' => 429, 'nombre_urbanizacion' => 'UTAMA', 'Nrodistrito' => 7],
            ['id' => 430, 'nombre_urbanizacion' => 'SEÑOR DE LAGUNAS', 'Nrodistrito' => 7],
            ['id' => 431, 'nombre_urbanizacion' => 'LAS  LOMAS', 'Nrodistrito' => 7],
            ['id' => 432, 'nombre_urbanizacion' => 'JULIAN APAZA', 'Nrodistrito' => 7],
            ['id' => 433, 'nombre_urbanizacion' => 'PARAISO SAN ROQUE', 'Nrodistrito' => 7],
            ['id' => 434, 'nombre_urbanizacion' => '14 DE ENERO LAGUNAS', 'Nrodistrito' => 7],
            ['id' => 435, 'nombre_urbanizacion' => 'BELLO HORIZONTE LAGUNAS', 'Nrodistrito' => 7],
            ['id' => 436, 'nombre_urbanizacion' => 'LOTEO SANTA ROSA', 'Nrodistrito' => 7],
            ['id' => 437, 'nombre_urbanizacion' => 'FORTALEZA', 'Nrodistrito' => 7],
            ['id' => 438, 'nombre_urbanizacion' => 'SAN ANTONIO SECTOR A', 'Nrodistrito' => 7],
            ['id' => 439, 'nombre_urbanizacion' => 'VILA VILA', 'Nrodistrito' => 7],
            ['id' => 440, 'nombre_urbanizacion' => 'SAN CRISPIN', 'Nrodistrito' => 7],
            ['id' => 441, 'nombre_urbanizacion' => 'SAN ANTONIO SECTOR B', 'Nrodistrito' => 7],
            ['id' => 442, 'nombre_urbanizacion' => 'EL SALVADOR', 'Nrodistrito' => 7],
            ['id' => 443, 'nombre_urbanizacion' => 'VALLE HERMOSO II', 'Nrodistrito' => 7],
            ['id' => 444, 'nombre_urbanizacion' => 'VALLE HERMOSO', 'Nrodistrito' => 7],
            ['id' => 445, 'nombre_urbanizacion' => 'REBECA DARIA', 'Nrodistrito' => 7],
            ['id' => 446, 'nombre_urbanizacion' => 'LOTEO DE HILDA AGUEDA GUTIERREZ VDA. DE JIMENEZ', 'Nrodistrito' => 7],
            ['id' => 447, 'nombre_urbanizacion' => 'SAN ANTONIO', 'Nrodistrito' => 7],
            ['id' => 448, 'nombre_urbanizacion' => 'LOTEO UTAMA', 'Nrodistrito' => 7],
            ['id' => 449, 'nombre_urbanizacion' => 'NORTE LAGUNA', 'Nrodistrito' => 7],
            ['id' => 450, 'nombre_urbanizacion' => 'EL PROGRESO', 'Nrodistrito' => 7],
            ['id' => 451, 'nombre_urbanizacion' => 'ANEXO 14 DE ENERO LAGUNA', 'Nrodistrito' => 7],
            ['id' => 452, 'nombre_urbanizacion' => 'LOTEO ANEXO SAN JUAN I', 'Nrodistrito' => 7],
            ['id' => 453, 'nombre_urbanizacion' => 'LAS VEGAS', 'Nrodistrito' => 7],
            ['id' => 454, 'nombre_urbanizacion' => 'NUEVO AMANECER', 'Nrodistrito' => 7],
            ['id' => 455, 'nombre_urbanizacion' => 'ANEXO BELLA VISTA', 'Nrodistrito' => 7],
            ['id' => 456, 'nombre_urbanizacion' => 'ALFA', 'Nrodistrito' => 7],
            ['id' => 457, 'nombre_urbanizacion' => 'JULIAN APAZA II', 'Nrodistrito' => 7],
            ['id' => 458, 'nombre_urbanizacion' => '21 DE OCTUBRE \"B\"', 'Nrodistrito' => 7],
            ['id' => 459, 'nombre_urbanizacion' => '2 DE JULIO', 'Nrodistrito' => 7],
            ['id' => 460, 'nombre_urbanizacion' => 'LOTEO CAMPO VERDE', 'Nrodistrito' => 7],
            ['id' => 461, 'nombre_urbanizacion' => 'RENACER KOLLA', 'Nrodistrito' => 7],
            ['id' => 462, 'nombre_urbanizacion' => '29 DE JUNIO', 'Nrodistrito' => 7],
            ['id' => 463, 'nombre_urbanizacion' => '5 DE JULIO', 'Nrodistrito' => 7],
            ['id' => 464, 'nombre_urbanizacion' => 'SAN ALBERTO SAN ROQUE', 'Nrodistrito' => 7],
            ['id' => 465, 'nombre_urbanizacion' => 'ANEXO VELLA VISTA SUR', 'Nrodistrito' => 7],
            ['id' => 466, 'nombre_urbanizacion' => 'FLOR MERY', 'Nrodistrito' => 12],
            ['id' => 467, 'nombre_urbanizacion' => 'COPACABANA', 'Nrodistrito' => 12],
            ['id' => 468, 'nombre_urbanizacion' => 'SANTA FE', 'Nrodistrito' => 7],
            ['id' => 469, 'nombre_urbanizacion' => 'BARRIO LINDO SAN ROQUE', 'Nrodistrito' => 7],
            ['id' => 470, 'nombre_urbanizacion' => 'SAN LORENZO', 'Nrodistrito' => 7],
            ['id' => 471, 'nombre_urbanizacion' => 'LOTEO TENORIO', 'Nrodistrito' => 8],
            ['id' => 472, 'nombre_urbanizacion' => 'SAN JUAN CUMARAVI 2DO', 'Nrodistrito' => 8],
            ['id' => 473, 'nombre_urbanizacion' => 'LAS FLORES', 'Nrodistrito' => 8],
            ['id' => 474, 'nombre_urbanizacion' => 'LOTEO EXCOMUNIDAD PUCARANI SECTOR CALLIPAMPA', 'Nrodistrito' => 8],
            ['id' => 475, 'nombre_urbanizacion' => 'JARDIN MAXIMA', 'Nrodistrito' => 8],
            ['id' => 476, 'nombre_urbanizacion' => 'SAN ANTONIO', 'Nrodistrito' => 8],
            ['id' => 477, 'nombre_urbanizacion' => 'SEÑOR DE LA CRUZ', 'Nrodistrito' => 8],
            ['id' => 478, 'nombre_urbanizacion' => 'BELLA VISTA', 'Nrodistrito' => 8],
            ['id' => 479, 'nombre_urbanizacion' => 'SAN MIGUEL SENKATA', 'Nrodistrito' => 8],
            ['id' => 480, 'nombre_urbanizacion' => 'LOTEO PALOS BLANCOS', 'Nrodistrito' => 8],
            ['id' => 481, 'nombre_urbanizacion' => 'RETAMAS III', 'Nrodistrito' => 8],
            ['id' => 482, 'nombre_urbanizacion' => 'UNION Y PROGRESO', 'Nrodistrito' => 8],
            ['id' => 483, 'nombre_urbanizacion' => 'BOLIVIA', 'Nrodistrito' => 8],
            ['id' => 484, 'nombre_urbanizacion' => 'UNIFICADA II', 'Nrodistrito' => 8],
            ['id' => 485, 'nombre_urbanizacion' => 'EMANUEL', 'Nrodistrito' => 8],
            ['id' => 486, 'nombre_urbanizacion' => 'TARAPACA \"A\"', 'Nrodistrito' => 8],
            ['id' => 487, 'nombre_urbanizacion' => 'TARAPACA \"D\"', 'Nrodistrito' => 8],
            ['id' => 488, 'nombre_urbanizacion' => 'CRISTAL III', 'Nrodistrito' => 8],
            ['id' => 489, 'nombre_urbanizacion' => 'SAN JORGE', 'Nrodistrito' => 8],
            ['id' => 490, 'nombre_urbanizacion' => 'LOTEO ANEXO URKUPIÑA III', 'Nrodistrito' => 8],
            ['id' => 491, 'nombre_urbanizacion' => 'VIDA ETERNA', 'Nrodistrito' => 8],
            ['id' => 492, 'nombre_urbanizacion' => 'SAN BUENAVENTURA', 'Nrodistrito' => 8],
            ['id' => 493, 'nombre_urbanizacion' => 'JUNTUHUMA FABRIL COBIJA', 'Nrodistrito' => 8],
            ['id' => 494, 'nombre_urbanizacion' => 'SENKATA PARCOPATA', 'Nrodistrito' => 8],
            ['id' => 495, 'nombre_urbanizacion' => '13 DE NOVIEMBRE', 'Nrodistrito' => 8],
            ['id' => 496, 'nombre_urbanizacion' => 'COMPLEMENTO FABRIL', 'Nrodistrito' => 8],
            ['id' => 497, 'nombre_urbanizacion' => 'URKUPIÑA III', 'Nrodistrito' => 8],
            ['id' => 498, 'nombre_urbanizacion' => 'SANTA FE', 'Nrodistrito' => 8],
            ['id' => 499, 'nombre_urbanizacion' => 'APOSTOL SANTIAGO', 'Nrodistrito' => 8],
            ['id' => 500, 'nombre_urbanizacion' => 'LOTEO GENERAL PANDO ANEXO II', 'Nrodistrito' => 8],
            ['id' => 501, 'nombre_urbanizacion' => '25 DE DICIEMBRE', 'Nrodistrito' => 8],
            ['id' => 502, 'nombre_urbanizacion' => 'MIRADOR', 'Nrodistrito' => 8],
            ['id' => 503, 'nombre_urbanizacion' => '14 DE SEPTIEMBRE', 'Nrodistrito' => 8],
            ['id' => 504, 'nombre_urbanizacion' => 'LUIS ESPINAL NUEVO VENTILLA', 'Nrodistrito' => 8],
            ['id' => 505, 'nombre_urbanizacion' => 'ROSEDAL VENTILLA', 'Nrodistrito' => 8],
            ['id' => 506, 'nombre_urbanizacion' => '23 DE MARZO', 'Nrodistrito' => 8],
            ['id' => 507, 'nombre_urbanizacion' => 'MODELO VENTILLA', 'Nrodistrito' => 8],
            ['id' => 508, 'nombre_urbanizacion' => 'SANTOS', 'Nrodistrito' => 8],
            ['id' => 509, 'nombre_urbanizacion' => 'PRADOS DE VENTILLA', 'Nrodistrito' => 8],
            ['id' => 510, 'nombre_urbanizacion' => 'ALTO MIRAFLORES', 'Nrodistrito' => 8],
            ['id' => 511, 'nombre_urbanizacion' => '31 DE OCTUBRE TARAPACA', 'Nrodistrito' => 8],
            ['id' => 512, 'nombre_urbanizacion' => 'VIRGEN DEL SOCAVON', 'Nrodistrito' => 8],
            ['id' => 513, 'nombre_urbanizacion' => 'VILLA PAULINA', 'Nrodistrito' => 8],
            ['id' => 514, 'nombre_urbanizacion' => '2 DE FEBRERO', 'Nrodistrito' => 8],
            ['id' => 515, 'nombre_urbanizacion' => 'VENTILLA I', 'Nrodistrito' => 8],
            ['id' => 516, 'nombre_urbanizacion' => 'VICTORIA', 'Nrodistrito' => 8],
            ['id' => 517, 'nombre_urbanizacion' => '8 DE ENERO-JUTU HUMA', 'Nrodistrito' => 8],
            ['id' => 518, 'nombre_urbanizacion' => '2 DE FEBRERO JUNTUHUMA', 'Nrodistrito' => 8],
            ['id' => 519, 'nombre_urbanizacion' => 'ANEXO 8 DE ENERO', 'Nrodistrito' => 8],
            ['id' => 520, 'nombre_urbanizacion' => 'COMPLEMENTO 8 DE ENERO', 'Nrodistrito' => 8],
            ['id' => 521, 'nombre_urbanizacion' => 'FABRIL JUNTUHUMA SECTOR 2', 'Nrodistrito' => 8],
            ['id' => 522, 'nombre_urbanizacion' => 'FABRIL JUNTUHUMA SECTOR 1', 'Nrodistrito' => 8],
            ['id' => 523, 'nombre_urbanizacion' => 'OLIVOS', 'Nrodistrito' => 8],
            ['id' => 524, 'nombre_urbanizacion' => '23 DE ENERO UNIFICADA', 'Nrodistrito' => 8],
            ['id' => 525, 'nombre_urbanizacion' => 'PARCOPATA 90', 'Nrodistrito' => 8],
            ['id' => 526, 'nombre_urbanizacion' => 'VILLA BELEN', 'Nrodistrito' => 8],
            ['id' => 527, 'nombre_urbanizacion' => 'NESTOR PAZ ZAMORA', 'Nrodistrito' => 8],
            ['id' => 528, 'nombre_urbanizacion' => '16 DE NOVIEMBRE', 'Nrodistrito' => 8],
            ['id' => 529, 'nombre_urbanizacion' => 'POLONIA', 'Nrodistrito' => 8],
            ['id' => 530, 'nombre_urbanizacion' => 'ANEXO 16 DE NOVIEMBRE', 'Nrodistrito' => 8],
            ['id' => 531, 'nombre_urbanizacion' => 'SAN CRISTOBAL', 'Nrodistrito' => 8],
            ['id' => 532, 'nombre_urbanizacion' => 'LITORAL SENKATA', 'Nrodistrito' => 8],
            ['id' => 533, 'nombre_urbanizacion' => 'SENKATA EXCOMUNIDAD PUCARANI', 'Nrodistrito' => 8],
            ['id' => 534, 'nombre_urbanizacion' => 'SAN PEDRO DE SENKATA', 'Nrodistrito' => 8],
            ['id' => 535, 'nombre_urbanizacion' => 'ANEXO SENKATA  PUCARANI', 'Nrodistrito' => 8],
            ['id' => 536, 'nombre_urbanizacion' => 'SAN PEDRO II', 'Nrodistrito' => 8],
            ['id' => 537, 'nombre_urbanizacion' => 'SAN PEDRO A SENKATA', 'Nrodistrito' => 8],
            ['id' => 538, 'nombre_urbanizacion' => 'TADEO', 'Nrodistrito' => 8],
            ['id' => 539, 'nombre_urbanizacion' => 'NAVAL', 'Nrodistrito' => 8],
            ['id' => 540, 'nombre_urbanizacion' => 'VILLA IMPERIAL', 'Nrodistrito' => 8],
            ['id' => 541, 'nombre_urbanizacion' => 'ILLIMANI', 'Nrodistrito' => 8],
            ['id' => 542, 'nombre_urbanizacion' => '27 DE ABRIL', 'Nrodistrito' => 8],
            ['id' => 543, 'nombre_urbanizacion' => 'VILLA ENCARNACION', 'Nrodistrito' => 8],
            ['id' => 544, 'nombre_urbanizacion' => 'MUCOPOL', 'Nrodistrito' => 8],
            ['id' => 545, 'nombre_urbanizacion' => 'SAN CARLOS', 'Nrodistrito' => 8],
            ['id' => 546, 'nombre_urbanizacion' => 'CRISTAL I', 'Nrodistrito' => 8],
            ['id' => 547, 'nombre_urbanizacion' => 'LA PAZ', 'Nrodistrito' => 8],
            ['id' => 548, 'nombre_urbanizacion' => 'CHIJIMARCA', 'Nrodistrito' => 8],
            ['id' => 549, 'nombre_urbanizacion' => 'SAN FRANCISCO II', 'Nrodistrito' => 8],
            ['id' => 550, 'nombre_urbanizacion' => 'JUANCITO PINTO', 'Nrodistrito' => 8],
            ['id' => 551, 'nombre_urbanizacion' => 'COMPLEMENTO SENKATA 79', 'Nrodistrito' => 8],
            ['id' => 552, 'nombre_urbanizacion' => 'INGAVI \"B\"', 'Nrodistrito' => 8],
            ['id' => 553, 'nombre_urbanizacion' => 'SAN FRANCISCO', 'Nrodistrito' => 8],
            ['id' => 554, 'nombre_urbanizacion' => 'SAN MIGUEL PATACIRCA', 'Nrodistrito' => 8],
            ['id' => 555, 'nombre_urbanizacion' => 'SAN SEBASTIAN SECTOR II', 'Nrodistrito' => 8],
            ['id' => 556, 'nombre_urbanizacion' => 'SAN SEBASTIAN SECCION II DESGLOSE A', 'Nrodistrito' => 8],
            ['id' => 557, 'nombre_urbanizacion' => 'SAN NICOLAS CHURINIQUELAPAMPA', 'Nrodistrito' => 8],
            ['id' => 558, 'nombre_urbanizacion' => 'SAN SILVESTRE II', 'Nrodistrito' => 8],
            ['id' => 559, 'nombre_urbanizacion' => 'CRISTAL II', 'Nrodistrito' => 8],
            ['id' => 560, 'nombre_urbanizacion' => 'LAS NIEVES', 'Nrodistrito' => 8],
            ['id' => 561, 'nombre_urbanizacion' => 'INTI RAYMI', 'Nrodistrito' => 8],
            ['id' => 562, 'nombre_urbanizacion' => 'INTI RAYMI II', 'Nrodistrito' => 8],
            ['id' => 563, 'nombre_urbanizacion' => 'SANTISIMA TRINIDAD', 'Nrodistrito' => 8],
            ['id' => 564, 'nombre_urbanizacion' => 'ANTOFAGASTA', 'Nrodistrito' => 8],
            ['id' => 565, 'nombre_urbanizacion' => 'SAN PEDRO SAN PABLO ANEXO SAN PABLO', 'Nrodistrito' => 8],
            ['id' => 566, 'nombre_urbanizacion' => 'SAN SEBASTIAN  I', 'Nrodistrito' => 8],
            ['id' => 567, 'nombre_urbanizacion' => 'CHAYANTA', 'Nrodistrito' => 8],
            ['id' => 568, 'nombre_urbanizacion' => '27 DE MAYO SENKATA', 'Nrodistrito' => 8],
            ['id' => 569, 'nombre_urbanizacion' => '14 DE MAYO', 'Nrodistrito' => 8],
            ['id' => 570, 'nombre_urbanizacion' => 'YACIMIENTOS PRETOLIFEROS FISCALES BOLIVIANOS', 'Nrodistrito' => 8],
            ['id' => 571, 'nombre_urbanizacion' => 'PANORAMICA II', 'Nrodistrito' => 8],
            ['id' => 572, 'nombre_urbanizacion' => '25 DE JULIO SENKATA', 'Nrodistrito' => 8],
            ['id' => 573, 'nombre_urbanizacion' => 'VIRGEN DE COPACABANA', 'Nrodistrito' => 8],
            ['id' => 574, 'nombre_urbanizacion' => 'ANDINO SENKATA', 'Nrodistrito' => 8],
            ['id' => 575, 'nombre_urbanizacion' => 'SAN LUIS  SENKATA', 'Nrodistrito' => 8],
            ['id' => 576, 'nombre_urbanizacion' => 'ANEXO II 25 DE JULIO', 'Nrodistrito' => 8],
            ['id' => 577, 'nombre_urbanizacion' => 'SAN PEDRO', 'Nrodistrito' => 8],
            ['id' => 578, 'nombre_urbanizacion' => '18 DE DICIEMBRE', 'Nrodistrito' => 8],
            ['id' => 579, 'nombre_urbanizacion' => 'ATIPIRIS', 'Nrodistrito' => 8],
            ['id' => 580, 'nombre_urbanizacion' => '6 DE AGOSTO', 'Nrodistrito' => 8],
            ['id' => 581, 'nombre_urbanizacion' => 'VIRGEN DE URKUPIÃ‘A', 'Nrodistrito' => 8],
            ['id' => 582, 'nombre_urbanizacion' => 'RETAMAS 1', 'Nrodistrito' => 8],
            ['id' => 583, 'nombre_urbanizacion' => 'LOS PINOS SENKATA', 'Nrodistrito' => 8],
            ['id' => 584, 'nombre_urbanizacion' => '30 DE AGOSTO', 'Nrodistrito' => 8],
            ['id' => 585, 'nombre_urbanizacion' => 'ANEXO ATIPIRIS', 'Nrodistrito' => 8],
            ['id' => 586, 'nombre_urbanizacion' => 'FLORIDA SENKATA', 'Nrodistrito' => 8],
            ['id' => 587, 'nombre_urbanizacion' => 'MIRADOR ATIPIRIS', 'Nrodistrito' => 8],
            ['id' => 588, 'nombre_urbanizacion' => 'VIRGEN DEL CARMEN', 'Nrodistrito' => 8],
            ['id' => 589, 'nombre_urbanizacion' => 'GENERAL PANDO', 'Nrodistrito' => 8],
            ['id' => 590, 'nombre_urbanizacion' => 'VILLA MERCEDES U.V. \"A\"', 'Nrodistrito' => 8],
            ['id' => 591, 'nombre_urbanizacion' => 'VILLA MERCEDES U.V. \"B\"', 'Nrodistrito' => 8],
            ['id' => 592, 'nombre_urbanizacion' => 'VILLA MERCEDES U.V. \"C\"', 'Nrodistrito' => 8],
            ['id' => 593, 'nombre_urbanizacion' => 'ANEXO SAN SIMON', 'Nrodistrito' => 7],
            ['id' => 594, 'nombre_urbanizacion' => 'LOTEO ANEXO COPACABANA', 'Nrodistrito' => 7],
            ['id' => 595, 'nombre_urbanizacion' => 'PAN DE VIDA', 'Nrodistrito' => 14],
            ['id' => 596, 'nombre_urbanizacion' => 'LOTEO SAN ANTONIO', 'Nrodistrito' => 7],
            ['id' => 597, 'nombre_urbanizacion' => '7 DE ABRIL', 'Nrodistrito' => 7],
            ['id' => 598, 'nombre_urbanizacion' => 'ROSARIO CENTRAL', 'Nrodistrito' => 8],
            ['id' => 599, 'nombre_urbanizacion' => 'LOTEO SANTA LUCIA', 'Nrodistrito' => 8],
            ['id' => 600, 'nombre_urbanizacion' => 'COMPLEMENTO 25 DE JULIO SENKATA', 'Nrodistrito' => 8],
            ['id' => 601, 'nombre_urbanizacion' => 'EUCALIPTUS II', 'Nrodistrito' => 8],
            ['id' => 602, 'nombre_urbanizacion' => 'LOTEO VILLA JULIANA', 'Nrodistrito' => 8],
            ['id' => 603, 'nombre_urbanizacion' => 'NUEVA ESPERANZA', 'Nrodistrito' => 8],
            ['id' => 604, 'nombre_urbanizacion' => 'ANEXO VILLA JULIANA', 'Nrodistrito' => 8],
            ['id' => 605, 'nombre_urbanizacion' => 'SENKATA 79', 'Nrodistrito' => 8],
            ['id' => 606, 'nombre_urbanizacion' => 'JUNTUHUMA I LAS RETAMAS', 'Nrodistrito' => 8],
            ['id' => 607, 'nombre_urbanizacion' => '27 DE SEPTIEMBRE', 'Nrodistrito' => 8],
            ['id' => 608, 'nombre_urbanizacion' => 'UNIFICADA POTOSI SENKATA', 'Nrodistrito' => 8],
            ['id' => 609, 'nombre_urbanizacion' => 'SAN JOSE III', 'Nrodistrito' => 8],
            ['id' => 610, 'nombre_urbanizacion' => 'DALU', 'Nrodistrito' => 8],
            ['id' => 611, 'nombre_urbanizacion' => 'DIGNIDAD', 'Nrodistrito' => 8],
            ['id' => 612, 'nombre_urbanizacion' => 'SAN ANDRES', 'Nrodistrito' => 8],
            ['id' => 613, 'nombre_urbanizacion' => 'ECOLOGICOS LOS PINOS', 'Nrodistrito' => 8],
            ['id' => 614, 'nombre_urbanizacion' => 'UTAMAHUA', 'Nrodistrito' => 8],
            ['id' => 615, 'nombre_urbanizacion' => '12 DE ABRIL', 'Nrodistrito' => 8],
            ['id' => 616, 'nombre_urbanizacion' => '29 DE JUNIO', 'Nrodistrito' => 8],
            ['id' => 617, 'nombre_urbanizacion' => 'PERCY REA PATZI', 'Nrodistrito' => 8],
            ['id' => 618, 'nombre_urbanizacion' => 'RETAMAS II', 'Nrodistrito' => 8],
            ['id' => 619, 'nombre_urbanizacion' => 'JATITA PAMPA', 'Nrodistrito' => 8],
            ['id' => 620, 'nombre_urbanizacion' => 'VIRGEN DE FATIMA', 'Nrodistrito' => 8],
            ['id' => 621, 'nombre_urbanizacion' => 'MAX FERNANDEZ', 'Nrodistrito' => 8],
            ['id' => 622, 'nombre_urbanizacion' => 'NOEL MENDOZA MIRANDA', 'Nrodistrito' => 8],
            ['id' => 623, 'nombre_urbanizacion' => 'PARAISO II', 'Nrodistrito' => 8],
            ['id' => 624, 'nombre_urbanizacion' => 'SEÑOR DE MAYO', 'Nrodistrito' => 8],
            ['id' => 625, 'nombre_urbanizacion' => 'ANEXO URKUPIÑA', 'Nrodistrito' => 8],
            ['id' => 626, 'nombre_urbanizacion' => 'CALIFORNIA', 'Nrodistrito' => 8],
            ['id' => 627, 'nombre_urbanizacion' => 'LOS JARDINES', 'Nrodistrito' => 8],
            ['id' => 628, 'nombre_urbanizacion' => 'ADJUDICATARIOS MINA CHOJLLA', 'Nrodistrito' => 8],
            ['id' => 629, 'nombre_urbanizacion' => 'RESIDENCIAL LLONTOP', 'Nrodistrito' => 8],
            ['id' => 630, 'nombre_urbanizacion' => 'SAN JOSE II', 'Nrodistrito' => 8],
            ['id' => 631, 'nombre_urbanizacion' => 'PARAISO I', 'Nrodistrito' => 8],
            ['id' => 632, 'nombre_urbanizacion' => 'ESTRELLA DEL NORTE', 'Nrodistrito' => 8],
            ['id' => 633, 'nombre_urbanizacion' => 'ESTRELLA DEL NORTE II', 'Nrodistrito' => 8],
            ['id' => 634, 'nombre_urbanizacion' => 'ANEXO PUCARANI SENKATA', 'Nrodistrito' => 8],
            ['id' => 635, 'nombre_urbanizacion' => 'SAN MARTIN', 'Nrodistrito' => 8],
            ['id' => 636, 'nombre_urbanizacion' => 'CONJUNTO HABITACIONAL CHIJINI 2', 'Nrodistrito' => 12],
            ['id' => 637, 'nombre_urbanizacion' => 'SAN FELIPE', 'Nrodistrito' => 12],
            ['id' => 638, 'nombre_urbanizacion' => 'CHIJINI CHICO II', 'Nrodistrito' => 12],
            ['id' => 639, 'nombre_urbanizacion' => 'CONJUNTO HABITACIONAL CHIJINI', 'Nrodistrito' => 12],
            ['id' => 640, 'nombre_urbanizacion' => 'COPACABANA FONVIS SECTOR XI', 'Nrodistrito' => 8],
            ['id' => 641, 'nombre_urbanizacion' => 'SAN FELIPE DE SEQUE SEC. 1 MNZ 22', 'Nrodistrito' => 4],
            ['id' => 642, 'nombre_urbanizacion' => 'INTI', 'Nrodistrito' => 12],
            ['id' => 643, 'nombre_urbanizacion' => 'CHIJINI CHICO', 'Nrodistrito' => 12],
            ['id' => 644, 'nombre_urbanizacion' => '6 DE AGOSTO CHIJINI ALTO', 'Nrodistrito' => 12],
            ['id' => 645, 'nombre_urbanizacion' => 'RIVERO', 'Nrodistrito' => 12],
            ['id' => 646, 'nombre_urbanizacion' => 'CHIJINI CHICO UNIDA VECINAL  \"A\"', 'Nrodistrito' => 12],
            ['id' => 647, 'nombre_urbanizacion' => 'SEÑOR DE EXALTACION  \"B\"', 'Nrodistrito' => 12],
            ['id' => 648, 'nombre_urbanizacion' => 'SAN MARTIN DE PORRES', 'Nrodistrito' => 12],
            ['id' => 649, 'nombre_urbanizacion' => 'SAN SALVADOR II', 'Nrodistrito' => 12],
            ['id' => 650, 'nombre_urbanizacion' => 'SEÑOR DE EXALTACION', 'Nrodistrito' => 12],
            ['id' => 651, 'nombre_urbanizacion' => 'NUEVO CHIJINI', 'Nrodistrito' => 12],
            ['id' => 652, 'nombre_urbanizacion' => 'SAN LORENZO', 'Nrodistrito' => 12],
            ['id' => 653, 'nombre_urbanizacion' => 'CANDELARIA', 'Nrodistrito' => 12],
            ['id' => 654, 'nombre_urbanizacion' => 'CHIJINI ALTO', 'Nrodistrito' => 12],
            ['id' => 655, 'nombre_urbanizacion' => 'LAS RETAMAS I', 'Nrodistrito' => 12],
            ['id' => 656, 'nombre_urbanizacion' => 'VILLA AIDITA', 'Nrodistrito' => 12],
            ['id' => 657, 'nombre_urbanizacion' => 'FATRAVI', 'Nrodistrito' => 12],
            ['id' => 658, 'nombre_urbanizacion' => 'NUCLEO VECINAL CHIJINI ALTO', 'Nrodistrito' => 12],
            ['id' => 659, 'nombre_urbanizacion' => 'NUEVA JERUSALEN', 'Nrodistrito' => 12],
            ['id' => 660, 'nombre_urbanizacion' => 'SAN CARLOS', 'Nrodistrito' => 12],
            ['id' => 661, 'nombre_urbanizacion' => 'SAN MARTIN  \"B\"', 'Nrodistrito' => 12],
            ['id' => 662, 'nombre_urbanizacion' => 'SANTA MARIA', 'Nrodistrito' => 12],
            ['id' => 663, 'nombre_urbanizacion' => 'TRES MARIAS', 'Nrodistrito' => 12],
            ['id' => 664, 'nombre_urbanizacion' => 'VILLA COLQUIRI', 'Nrodistrito' => 12],
            ['id' => 665, 'nombre_urbanizacion' => 'SAN ANTONIO', 'Nrodistrito' => 12],
            ['id' => 666, 'nombre_urbanizacion' => 'CIUDADELA JARDIN', 'Nrodistrito' => 12],
            ['id' => 667, 'nombre_urbanizacion' => 'APOLO I', 'Nrodistrito' => 12],
            ['id' => 668, 'nombre_urbanizacion' => 'ALTO CHIJINI', 'Nrodistrito' => 12],
            ['id' => 669, 'nombre_urbanizacion' => 'COPACABANA V', 'Nrodistrito' => 12],
            ['id' => 670, 'nombre_urbanizacion' => 'FATIMA', 'Nrodistrito' => 12],
            ['id' => 671, 'nombre_urbanizacion' => 'AMERICA  ALTO CHIJINI', 'Nrodistrito' => 12],
            ['id' => 672, 'nombre_urbanizacion' => 'SAN PEDRO LAJA', 'Nrodistrito' => 12],
            ['id' => 673, 'nombre_urbanizacion' => 'SAN CARLOS AMPLIACION', 'Nrodistrito' => 12],
            ['id' => 674, 'nombre_urbanizacion' => '14 DE SEPTIEMBRE AMPLIACION', 'Nrodistrito' => 12],
            ['id' => 675, 'nombre_urbanizacion' => 'SAN LUIS II', 'Nrodistrito' => 12],
            ['id' => 676, 'nombre_urbanizacion' => 'SAN MARTIN DE PORRES AMPLIACION', 'Nrodistrito' => 12],
            ['id' => 677, 'nombre_urbanizacion' => 'AMPLIACIÃ“N SAN PEDRO DE LAJA', 'Nrodistrito' => 12],
            ['id' => 678, 'nombre_urbanizacion' => 'LAS PLAYAS', 'Nrodistrito' => 13],
            ['id' => 679, 'nombre_urbanizacion' => 'VICTORIA A3', 'Nrodistrito' => 13],
            ['id' => 680, 'nombre_urbanizacion' => 'VICTORIA A2', 'Nrodistrito' => 13],
            ['id' => 681, 'nombre_urbanizacion' => 'VICTORIA A1', 'Nrodistrito' => 13],
            ['id' => 682, 'nombre_urbanizacion' => 'CIUDADELA JARDIN', 'Nrodistrito' => 13],
            ['id' => 683, 'nombre_urbanizacion' => '21 DE ENERO', 'Nrodistrito' => 13],
            ['id' => 684, 'nombre_urbanizacion' => 'CRISTO VENCEDOR', 'Nrodistrito' => 14],
            ['id' => 685, 'nombre_urbanizacion' => 'EL VIÑA', 'Nrodistrito' => 14],
            ['id' => 686, 'nombre_urbanizacion' => 'COMPLEMENTO FRANZ TAMAYO SECTOR TARACO', 'Nrodistrito' => 14],
            ['id' => 687, 'nombre_urbanizacion' => 'LOTEO AMBORO', 'Nrodistrito' => 14],
            ['id' => 688, 'nombre_urbanizacion' => 'ANEXO VIRGEN DE COPACABANA', 'Nrodistrito' => 14],
            ['id' => 689, 'nombre_urbanizacion' => 'LUZ DEL ANDE', 'Nrodistrito' => 14],
            ['id' => 690, 'nombre_urbanizacion' => 'SAN JORGE', 'Nrodistrito' => 14],
            ['id' => 691, 'nombre_urbanizacion' => 'SEÑOR DE LA CRUZ INGENIO', 'Nrodistrito' => 14],
            ['id' => 692, 'nombre_urbanizacion' => 'BAUTISTA SAAVEDRA U.V.I.', 'Nrodistrito' => 14],
            ['id' => 693, 'nombre_urbanizacion' => 'LOTEO VIRGEN DE URKUPIÃ‘A', 'Nrodistrito' => 14],
            ['id' => 694, 'nombre_urbanizacion' => 'FRANZ TAMAYO SECTOR \"D\"', 'Nrodistrito' => 14],
            ['id' => 695, 'nombre_urbanizacion' => 'BAUTISTA SAAVEDRA U.V.B-2', 'Nrodistrito' => 14],
            ['id' => 696, 'nombre_urbanizacion' => 'COMPLEMENTO LOS PINOS', 'Nrodistrito' => 14],
            ['id' => 697, 'nombre_urbanizacion' => 'FRANZ TAMAYO SECTOR \"C\"', 'Nrodistrito' => 14],
            ['id' => 698, 'nombre_urbanizacion' => 'PATRICIA', 'Nrodistrito' => 14],
            ['id' => 699, 'nombre_urbanizacion' => 'FRANZ TAMAYO SECTOR \"B\"', 'Nrodistrito' => 14],
            ['id' => 700, 'nombre_urbanizacion' => 'ILLAMPU \"B\"', 'Nrodistrito' => 14],
            ['id' => 701, 'nombre_urbanizacion' => 'BAUTISTA SAAVEDRA U.V.\"A\"', 'Nrodistrito' => 14],
            ['id' => 702, 'nombre_urbanizacion' => 'PALESTINA', 'Nrodistrito' => 14],
            ['id' => 703, 'nombre_urbanizacion' => 'MARISCAL SUCRE ILLAMPU', 'Nrodistrito' => 14],
            ['id' => 704, 'nombre_urbanizacion' => 'FLOR DE ILLAMPU', 'Nrodistrito' => 14],
            ['id' => 705, 'nombre_urbanizacion' => 'VILLA EGUEZ', 'Nrodistrito' => 14],
            ['id' => 706, 'nombre_urbanizacion' => '30 DE SEPTIEMBRE MARISCAL SUCRE', 'Nrodistrito' => 14],
            ['id' => 707, 'nombre_urbanizacion' => 'NUEVOS HORIZONTES NORTE', 'Nrodistrito' => 14],
            ['id' => 708, 'nombre_urbanizacion' => 'SAN MIGUEL ARCANGEL', 'Nrodistrito' => 14],
            ['id' => 709, 'nombre_urbanizacion' => 'BAUTISTA SAAVEDRA SECTOR SANTA MARIA', 'Nrodistrito' => 14],
            ['id' => 710, 'nombre_urbanizacion' => 'ANEXO BAUTISTA SAAVEDRA U.V. A', 'Nrodistrito' => 14],
            ['id' => 711, 'nombre_urbanizacion' => 'VILLA BOLIVAR \"D\" MANZANO 128', 'Nrodistrito' => 2],
            ['id' => 712, 'nombre_urbanizacion' => 'VILLA BOLIVAR \"D\"', 'Nrodistrito' => 2],
            ['id' => 713, 'nombre_urbanizacion' => 'VILLA CONCEPCION', 'Nrodistrito' => 2],
            ['id' => 714, 'nombre_urbanizacion' => 'PANORAMICA MIRADOR', 'Nrodistrito' => 2],
            ['id' => 715, 'nombre_urbanizacion' => 'VILLA SANTIAGO II', 'Nrodistrito' => 2],
            ['id' => 716, 'nombre_urbanizacion' => '6 DE JUNIO', 'Nrodistrito' => 2],
            ['id' => 717, 'nombre_urbanizacion' => 'EDUARDO AVAROA CALLIPAMPA', 'Nrodistrito' => 2],
            ['id' => 718, 'nombre_urbanizacion' => 'SAN JUAN', 'Nrodistrito' => 2],
            ['id' => 719, 'nombre_urbanizacion' => 'LOTEO KENKO PUCARANI', 'Nrodistrito' => 2],
            ['id' => 720, 'nombre_urbanizacion' => 'SAN MIGUEL DE PUCARANI ANEXO \"C\"', 'Nrodistrito' => 2],
            ['id' => 721, 'nombre_urbanizacion' => 'SAN MIGUEL DE PUCARANI ANEXO \"B\"', 'Nrodistrito' => 2],
            ['id' => 722, 'nombre_urbanizacion' => '18 DE MAYO SENKATA', 'Nrodistrito' => 2],
            ['id' => 723, 'nombre_urbanizacion' => 'COOPERATIVA AGRICOLA SUPER MERCADO LTDA.', 'Nrodistrito' => 2],
            ['id' => 724, 'nombre_urbanizacion' => 'PUCARANI AURORA', 'Nrodistrito' => 2],
            ['id' => 725, 'nombre_urbanizacion' => 'LOTEO LOS PINOS SAN MIGUEL', 'Nrodistrito' => 2],
            ['id' => 726, 'nombre_urbanizacion' => 'ASCINALCLAS', 'Nrodistrito' => 2],
            ['id' => 727, 'nombre_urbanizacion' => 'COOPERATIVA \"EL TEJAR\" CALLIPAMPA-SENKATA', 'Nrodistrito' => 2],
            ['id' => 728, 'nombre_urbanizacion' => 'VILLA BOLIVAR B', 'Nrodistrito' => 2],
            ['id' => 729, 'nombre_urbanizacion' => 'ALMAPAZ', 'Nrodistrito' => 2],
            ['id' => 730, 'nombre_urbanizacion' => 'BARRIO LINDO', 'Nrodistrito' => 2],
            ['id' => 731, 'nombre_urbanizacion' => 'LAS DELICIAS  II', 'Nrodistrito' => 2],
            ['id' => 732, 'nombre_urbanizacion' => 'GRAN PODER', 'Nrodistrito' => 2],
            ['id' => 733, 'nombre_urbanizacion' => 'ORO NEGRO', 'Nrodistrito' => 2],
            ['id' => 734, 'nombre_urbanizacion' => 'CUPILUPACA', 'Nrodistrito' => 2],
            ['id' => 735, 'nombre_urbanizacion' => 'EX COMBATIENTES', 'Nrodistrito' => 2],
            ['id' => 736, 'nombre_urbanizacion' => 'COMPLEMENTO BAUTISTA SAAVEDRA UNIDAD VECINAL A', 'Nrodistrito' => 14],
            ['id' => 737, 'nombre_urbanizacion' => 'FRANZ TAMAYO', 'Nrodistrito' => 14],
            ['id' => 738, 'nombre_urbanizacion' => 'BAUTISTA SAAVEDRA U.V. \"CH\"', 'Nrodistrito' => 14],
            ['id' => 739, 'nombre_urbanizacion' => 'MCAL. SUCRE BAJO MILLUNI SECTOR \"B\"', 'Nrodistrito' => 14],
            ['id' => 740, 'nombre_urbanizacion' => 'MCAL. SUCRE BAJO MILLUNI SECTOR C', 'Nrodistrito' => 14],
            ['id' => 741, 'nombre_urbanizacion' => 'EX COMUNIDAD MILLUNI BAJO', 'Nrodistrito' => 14],
            ['id' => 742, 'nombre_urbanizacion' => 'CAMPO GRANDE', 'Nrodistrito' => 14],
            ['id' => 743, 'nombre_urbanizacion' => 'LOS PINOS', 'Nrodistrito' => 14],
            ['id' => 744, 'nombre_urbanizacion' => 'COMPLEMENTO LOS PINOS', 'Nrodistrito' => 14],
            ['id' => 745, 'nombre_urbanizacion' => 'ILLAMPU II', 'Nrodistrito' => 14],
            ['id' => 746, 'nombre_urbanizacion' => 'PROLONGACION MARISCAL SUCRE ILLAMPU', 'Nrodistrito' => 14],
            ['id' => 747, 'nombre_urbanizacion' => 'SANTO TOMAS', 'Nrodistrito' => 14],
            ['id' => 748, 'nombre_urbanizacion' => 'LAS RETAMAS', 'Nrodistrito' => 14],
            ['id' => 749, 'nombre_urbanizacion' => 'LOTEO COMPLEMENTO MARISCAL SUCRE ILLAMPU', 'Nrodistrito' => 14],
            ['id' => 750, 'nombre_urbanizacion' => 'LOS PINOS II', 'Nrodistrito' => 14],
            ['id' => 751, 'nombre_urbanizacion' => 'FRANZ TAMAYO CENTRAL SECTOR FUNDAMENTAL', 'Nrodistrito' => 14],
            ['id' => 752, 'nombre_urbanizacion' => 'LOTEO 25 DE JULIO', 'Nrodistrito' => 7],
            ['id' => 753, 'nombre_urbanizacion' => 'VILLA  ASUNCION SAN PEDRO', 'Nrodistrito' => 2],
            ['id' => 754, 'nombre_urbanizacion' => 'WARA', 'Nrodistrito' => 2],
            ['id' => 755, 'nombre_urbanizacion' => 'SINDICATO DE COLECTIVEROS LITORAL', 'Nrodistrito' => 2],
            ['id' => 756, 'nombre_urbanizacion' => 'CORAZON DE JESUS', 'Nrodistrito' => 2],
            ['id' => 757, 'nombre_urbanizacion' => 'GUTIERREZ', 'Nrodistrito' => 14],
            ['id' => 758, 'nombre_urbanizacion' => 'VIRGEN DE COPACABANA MILLUNI BAJO', 'Nrodistrito' => 14],
            ['id' => 759, 'nombre_urbanizacion' => 'PUERTO CAMACHO', 'Nrodistrito' => 14],
            ['id' => 760, 'nombre_urbanizacion' => 'BAUTISTA SAAVEDRA U.V. \"C\" PLACA', 'Nrodistrito' => 14],
            ['id' => 761, 'nombre_urbanizacion' => 'BAUTISTA SAAVEDRA U.V. \"I\" PLACA VECINAL \"H\"', 'Nrodistrito' => 14],
            ['id' => 762, 'nombre_urbanizacion' => 'BAUTISTA SAAVEDRA U.V. \"G\"', 'Nrodistrito' => 14],
            ['id' => 763, 'nombre_urbanizacion' => 'BAUTISTA SAAVEDRA U.V. \"F\"', 'Nrodistrito' => 14],
            ['id' => 764, 'nombre_urbanizacion' => 'BAUTISTA SAAVEDRA U.V. \"E\"', 'Nrodistrito' => 14],
            ['id' => 765, 'nombre_urbanizacion' => 'SAN CARLOS', 'Nrodistrito' => 14],
            ['id' => 766, 'nombre_urbanizacion' => 'LOTEO ANEXO COOPERATIVA', 'Nrodistrito' => 14],
            ['id' => 767, 'nombre_urbanizacion' => 'VILLA COOPERATIVA NORTE', 'Nrodistrito' => 14],
            ['id' => 768, 'nombre_urbanizacion' => 'BAUTISTA SAAVEDRA U.V. \"D\"', 'Nrodistrito' => 14],
            ['id' => 769, 'nombre_urbanizacion' => 'BAUTISTA SAAVEDRA U.V. \"J\"', 'Nrodistrito' => 14],
            ['id' => 770, 'nombre_urbanizacion' => 'MANUEL RIGOBERTO PAREDES', 'Nrodistrito' => 14],
            ['id' => 771, 'nombre_urbanizacion' => 'ESTRELLA DEL NORTE', 'Nrodistrito' => 14],
            ['id' => 772, 'nombre_urbanizacion' => 'AD VENIR', 'Nrodistrito' => 14],
            ['id' => 773, 'nombre_urbanizacion' => 'FRANCO VALLE', 'Nrodistrito' => 14],
            ['id' => 774, 'nombre_urbanizacion' => 'LOTEO CUIMA', 'Nrodistrito' => 14],
            ['id' => 775, 'nombre_urbanizacion' => 'LOTEO FORTALEZA', 'Nrodistrito' => 14],
            ['id' => 776, 'nombre_urbanizacion' => 'LOTEO SECTOR SAN JUAN VILLA MCAL SUCRE', 'Nrodistrito' => 14],
            ['id' => 777, 'nombre_urbanizacion' => 'ANEXO ESTRELLA DEL NORTE', 'Nrodistrito' => 14],
            ['id' => 778, 'nombre_urbanizacion' => 'LOTEO MARISCAL SUCRE SECTOR SAN SALVADOR CHOJLLA', 'Nrodistrito' => 14],
            ['id' => 779, 'nombre_urbanizacion' => 'SAN CARLOS V', 'Nrodistrito' => 14],
            ['id' => 780, 'nombre_urbanizacion' => 'VILLA BALANZA', 'Nrodistrito' => 14],
            ['id' => 781, 'nombre_urbanizacion' => 'BAUTISTA SAAVEDRA U.V. B.', 'Nrodistrito' => 14],
            ['id' => 782, 'nombre_urbanizacion' => 'PANAMERICANA II (MILLUNI BAJO)', 'Nrodistrito' => 14],
            ['id' => 783, 'nombre_urbanizacion' => 'HICHUSIRCA CHICO DIVISION Y PARTICION', 'Nrodistrito' => 14],
            ['id' => 784, 'nombre_urbanizacion' => 'LAS LOMAS VILLA INGENIO', 'Nrodistrito' => 14],
            ['id' => 785, 'nombre_urbanizacion' => 'AGUA DE LA VIDA', 'Nrodistrito' => 14],
            ['id' => 786, 'nombre_urbanizacion' => 'EL PALMAR', 'Nrodistrito' => 14],
            ['id' => 787, 'nombre_urbanizacion' => 'MARISCAL SUCRE ILLAMPU I', 'Nrodistrito' => 14],
            ['id' => 788, 'nombre_urbanizacion' => 'LOTEO COOPERATIVA EL TEJAR (EL SALVADOR)', 'Nrodistrito' => 14],
            ['id' => 789, 'nombre_urbanizacion' => 'EL PORVENIR I', 'Nrodistrito' => 7],
            ['id' => 790, 'nombre_urbanizacion' => '12 DE OCTUBRE', 'Nrodistrito' => 1],
            ['id' => 791, 'nombre_urbanizacion' => 'VILLA BOLIVAR \"A\"', 'Nrodistrito' => 1],
            ['id' => 792, 'nombre_urbanizacion' => 'FARO MURILLO', 'Nrodistrito' => 1],
            ['id' => 793, 'nombre_urbanizacion' => 'ANEXO SANTA ROSA', 'Nrodistrito' => 1],
            ['id' => 794, 'nombre_urbanizacion' => 'SAN ALBERTO', 'Nrodistrito' => 8],
            ['id' => 795, 'nombre_urbanizacion' => 'COMPLEMENTO ROSAS PAMPA SECTOR 2', 'Nrodistrito' => 1],
            ['id' => 796, 'nombre_urbanizacion' => 'COMPLEMENTO ROSAS PAMPA 1', 'Nrodistrito' => 1],
            ['id' => 797, 'nombre_urbanizacion' => 'VILLA BOLIVAR YKK', 'Nrodistrito' => 1],
            ['id' => 798, 'nombre_urbanizacion' => 'COMPLEMENTO ROSAS PAMPA SECTOR 1', 'Nrodistrito' => 1],
            ['id' => 799, 'nombre_urbanizacion' => 'EL PORVENIR', 'Nrodistrito' => 2],
            ['id' => 800, 'nombre_urbanizacion' => 'VILLAZON', 'Nrodistrito' => 2],
            ['id' => 801, 'nombre_urbanizacion' => 'SINDICATO MIXTO DE VOLANTES YUNGAS', 'Nrodistrito' => 2],
            ['id' => 802, 'nombre_urbanizacion' => 'SANTA ROSA', 'Nrodistrito' => 1],
            ['id' => 803, 'nombre_urbanizacion' => 'TEJADA ALPACOMA BAJO', 'Nrodistrito' => 1],
            ['id' => 804, 'nombre_urbanizacion' => 'ANEXO FINAL ROSAS PAMPA', 'Nrodistrito' => 1],
            ['id' => 805, 'nombre_urbanizacion' => 'COMPLEMENTO SANTA ROSA', 'Nrodistrito' => 1],
            ['id' => 806, 'nombre_urbanizacion' => 'REGIMIENTO INGAVI', 'Nrodistrito' => 1],
            ['id' => 807, 'nombre_urbanizacion' => '31 DE OCTUBRE', 'Nrodistrito' => 1],
            ['id' => 808, 'nombre_urbanizacion' => 'VILLA EXSALTACION 1RA SECCION', 'Nrodistrito' => 1],
            ['id' => 809, 'nombre_urbanizacion' => 'VILLA EXALTACION 2DA SECCION', 'Nrodistrito' => 1],
            ['id' => 810, 'nombre_urbanizacion' => 'PEDRO DOMINGO MURILLO', 'Nrodistrito' => 2],
            ['id' => 811, 'nombre_urbanizacion' => 'VILLA AROMA', 'Nrodistrito' => 2],
            ['id' => 812, 'nombre_urbanizacion' => 'ALAMOS', 'Nrodistrito' => 8],
            ['id' => 813, 'nombre_urbanizacion' => 'ARCO IRIS', 'Nrodistrito' => 1],
            ['id' => 814, 'nombre_urbanizacion' => 'VILLA EXALTACION 3RA SECCION', 'Nrodistrito' => 1],
            ['id' => 815, 'nombre_urbanizacion' => 'VILLA ROSAS PAMPA', 'Nrodistrito' => 1],
            ['id' => 816, 'nombre_urbanizacion' => 'PLAN 328', 'Nrodistrito' => 1],
            ['id' => 817, 'nombre_urbanizacion' => 'PLAN 361', 'Nrodistrito' => 1],
            ['id' => 818, 'nombre_urbanizacion' => 'PLAN 482', 'Nrodistrito' => 1],
            ['id' => 819, 'nombre_urbanizacion' => 'NUEVOS HORIZONTES II', 'Nrodistrito' => 2],
            ['id' => 820, 'nombre_urbanizacion' => 'NUEVOS HORIZONTES III', 'Nrodistrito' => 2],
            ['id' => 821, 'nombre_urbanizacion' => 'NUEVOS HORIZONTES CONVIFAGC', 'Nrodistrito' => 2],
            ['id' => 822, 'nombre_urbanizacion' => 'JUNTA DE BENEFICIARIOS \"MILLUNI\"', 'Nrodistrito' => 2],
            ['id' => 823, 'nombre_urbanizacion' => '21 DE DICIEMBRE', 'Nrodistrito' => 2],
            ['id' => 824, 'nombre_urbanizacion' => 'ROSAS PAMPA INDUSTRIAL', 'Nrodistrito' => 2],
            ['id' => 825, 'nombre_urbanizacion' => 'LAS DELICIAS', 'Nrodistrito' => 2],
            ['id' => 826, 'nombre_urbanizacion' => 'ZONA FRANCA COMERCIAL', 'Nrodistrito' => 2],
            ['id' => 827, 'nombre_urbanizacion' => 'SANTA ISABEL', 'Nrodistrito' => 2],
            ['id' => 828, 'nombre_urbanizacion' => 'JANKO KALANI', 'Nrodistrito' => 2],
            ['id' => 829, 'nombre_urbanizacion' => 'EL KENKO', 'Nrodistrito' => 2],
            ['id' => 830, 'nombre_urbanizacion' => 'LOTEAMIENTO VILLA LUISA', 'Nrodistrito' => 2],
            ['id' => 831, 'nombre_urbanizacion' => 'VILLA BOLIVAR MUNICIPAL', 'Nrodistrito' => 2],
            ['id' => 832, 'nombre_urbanizacion' => 'SOLIDARIDAD', 'Nrodistrito' => 5],
            ['id' => 833, 'nombre_urbanizacion' => 'SATELITE PLAN 129', 'Nrodistrito' => 1],
            ['id' => 834, 'nombre_urbanizacion' => 'TEJADA RECTANGULAR', 'Nrodistrito' => 1],
            ['id' => 835, 'nombre_urbanizacion' => 'PLAN 405', 'Nrodistrito' => 1],
            ['id' => 836, 'nombre_urbanizacion' => 'PLAN 50 CINEMATOGRAFISTAS', 'Nrodistrito' => 1],
            ['id' => 837, 'nombre_urbanizacion' => 'PLAN 112', 'Nrodistrito' => 1],
            ['id' => 838, 'nombre_urbanizacion' => 'PLAN 220', 'Nrodistrito' => 1],
            ['id' => 839, 'nombre_urbanizacion' => 'PLAN 220', 'Nrodistrito' => 1],
            ['id' => 840, 'nombre_urbanizacion' => 'PLAN 361', 'Nrodistrito' => 1],
            ['id' => 841, 'nombre_urbanizacion' => 'PLAN 361', 'Nrodistrito' => 1],
            ['id' => 842, 'nombre_urbanizacion' => 'PLAN 175', 'Nrodistrito' => 1],
            ['id' => 843, 'nombre_urbanizacion' => 'TEJADA ALPACOMA', 'Nrodistrito' => 1],
            ['id' => 844, 'nombre_urbanizacion' => 'PLAN 220', 'Nrodistrito' => 1],
            ['id' => 845, 'nombre_urbanizacion' => 'PLAN 361', 'Nrodistrito' => 1],
            ['id' => 846, 'nombre_urbanizacion' => 'PLAN 97', 'Nrodistrito' => 1],
            ['id' => 847, 'nombre_urbanizacion' => 'PLAN 266', 'Nrodistrito' => 1],
            ['id' => 848, 'nombre_urbanizacion' => 'PLAN 561', 'Nrodistrito' => 1],
            ['id' => 849, 'nombre_urbanizacion' => 'PLAN 148', 'Nrodistrito' => 1],
            ['id' => 850, 'nombre_urbanizacion' => 'VILLA DOLORES SECTOR COVIMIN, FONVIS  en liquidacion', 'Nrodistrito' => 1],
            ['id' => 851, 'nombre_urbanizacion' => 'VILLA DOLORES', 'Nrodistrito' => 1],
            ['id' => 852, 'nombre_urbanizacion' => 'NUEVOS HORIZONTES I', 'Nrodistrito' => 2],
            ['id' => 853, 'nombre_urbanizacion' => 'SAN PATRICIO', 'Nrodistrito' => 7],
            ['id' => 854, 'nombre_urbanizacion' => 'LOTEO COMPLEMENTO BETHEL', 'Nrodistrito' => 7],
            ['id' => 855, 'nombre_urbanizacion' => 'BET-EL', 'Nrodistrito' => 7],
            ['id' => 856, 'nombre_urbanizacion' => 'SINDICATO COLECTIVEROS MIXTO VILLA VICTORIA', 'Nrodistrito' => 2],
            ['id' => 857, 'nombre_urbanizacion' => 'COPACABANA', 'Nrodistrito' => 2],
            ['id' => 858, 'nombre_urbanizacion' => 'LOTEO VILLA LUISA MANZANOS I-I1', 'Nrodistrito' => 2],
            ['id' => 859, 'nombre_urbanizacion' => 'ANEXO ROSAS PAMPA QUECHISLA', 'Nrodistrito' => 2],
            ['id' => 860, 'nombre_urbanizacion' => 'VILLA BOLIVAR', 'Nrodistrito' => 2],
            ['id' => 861, 'nombre_urbanizacion' => 'VILLA BOLIVAR FORNO', 'Nrodistrito' => 2],
            ['id' => 862, 'nombre_urbanizacion' => 'ANEXO VILLA BOLIVAR \"D\"', 'Nrodistrito' => 2],
            ['id' => 863, 'nombre_urbanizacion' => 'EDUARDO AVAROA', 'Nrodistrito' => 2],
            ['id' => 864, 'nombre_urbanizacion' => 'VILLA EL CARMEN', 'Nrodistrito' => 2],
            ['id' => 865, 'nombre_urbanizacion' => 'VILLA ELIZARDO PEREZ', 'Nrodistrito' => 2],
            ['id' => 866, 'nombre_urbanizacion' => 'VILLA BOLIVAR MUNICIPAL NORTE', 'Nrodistrito' => 2],
            ['id' => 867, 'nombre_urbanizacion' => 'VILLA BOLIVAR FORDELBE', 'Nrodistrito' => 2],
            ['id' => 868, 'nombre_urbanizacion' => 'VILLA BOLIVAR \"E\"', 'Nrodistrito' => 2],
            ['id' => 869, 'nombre_urbanizacion' => 'PANORAMICA I', 'Nrodistrito' => 2],
            ['id' => 870, 'nombre_urbanizacion' => 'PREFECTURA BOLIVAR', 'Nrodistrito' => 2],
            ['id' => 871, 'nombre_urbanizacion' => '10 DE ABRIL', 'Nrodistrito' => 2],
            ['id' => 872, 'nombre_urbanizacion' => 'PUCARANI INDUSTRIAL', 'Nrodistrito' => 2],
            ['id' => 873, 'nombre_urbanizacion' => 'SENAC - D1', 'Nrodistrito' => 2],
            ['id' => 874, 'nombre_urbanizacion' => 'LA PORTADA', 'Nrodistrito' => 2],
            ['id' => 875, 'nombre_urbanizacion' => 'CUPILUPACA CENTRAL', 'Nrodistrito' => 2],
            ['id' => 876, 'nombre_urbanizacion' => 'SAN MIGUEL DE PUCARANI', 'Nrodistrito' => 2],
            ['id' => 877, 'nombre_urbanizacion' => 'JUANA AZURDUY  DE PADILLA U.V.E.', 'Nrodistrito' => 4],
            ['id' => 878, 'nombre_urbanizacion' => 'JUANA AZURDUY  DE PADILLA U.V.D.', 'Nrodistrito' => 4],
            ['id' => 879, 'nombre_urbanizacion' => 'JUANA AZURDUY  DE PADILLA U.V.C.', 'Nrodistrito' => 4],
            ['id' => 880, 'nombre_urbanizacion' => 'SAN FELIPE DE SEQUE', 'Nrodistrito' => 4],
            ['id' => 881, 'nombre_urbanizacion' => 'VILLA FRANZ TAMAYO', 'Nrodistrito' => 4],
            ['id' => 882, 'nombre_urbanizacion' => 'RÍO SECO (YUNGUYO)', 'Nrodistrito' => 4],
            ['id' => 883, 'nombre_urbanizacion' => 'ANEXO RIO SECO EXTRANCA MANZANO \"A\"', 'Nrodistrito' => 4],
            ['id' => 884, 'nombre_urbanizacion' => 'GRAN PODER (RIO SECO)', 'Nrodistrito' => 4],
            ['id' => 885, 'nombre_urbanizacion' => 'MARISCAL SUCRE HICHUSIRCA CHICO PARTE SUR', 'Nrodistrito' => 4],
            ['id' => 886, 'nombre_urbanizacion' => 'COMPLEMENTO TUNARI', 'Nrodistrito' => 4],
            ['id' => 887, 'nombre_urbanizacion' => 'TUNARI FAB', 'Nrodistrito' => 4],
            ['id' => 888, 'nombre_urbanizacion' => 'VILLA TUNARI', 'Nrodistrito' => 4],
            ['id' => 889, 'nombre_urbanizacion' => 'VILLA  6 DE AGOSTO', 'Nrodistrito' => 4],
            ['id' => 890, 'nombre_urbanizacion' => '6 DE MARZO', 'Nrodistrito' => 4],
            ['id' => 891, 'nombre_urbanizacion' => 'VILLA NUEVA MARCA', 'Nrodistrito' => 4],
            ['id' => 892, 'nombre_urbanizacion' => 'PEDRO DOMINGO MURILLO 1ra SECCION', 'Nrodistrito' => 4],
            ['id' => 893, 'nombre_urbanizacion' => 'PEDRO DOMINGO MURILLO 2da SECCION', 'Nrodistrito' => 4],
            ['id' => 894, 'nombre_urbanizacion' => 'PEDRO DOMINGO MURILLO 3ra SECCION', 'Nrodistrito' => 4],
            ['id' => 895, 'nombre_urbanizacion' => 'PEDRO DOMINGO MURILLO 4ta SECCION', 'Nrodistrito' => 4],
            ['id' => 896, 'nombre_urbanizacion' => 'NUCLEO BRASIL', 'Nrodistrito' => 4],
            ['id' => 897, 'nombre_urbanizacion' => 'ARTESANOS  I  Y  II', 'Nrodistrito' => 4],
            ['id' => 898, 'nombre_urbanizacion' => 'VILLA YUNGUYO RIO SECO', 'Nrodistrito' => 4],
            ['id' => 899, 'nombre_urbanizacion' => 'RIO SECO SECTOR ESTRELLA DE BELEN', 'Nrodistrito' => 4],
            ['id' => 900, 'nombre_urbanizacion' => 'RIO SECO ANEXO  25 DE JULIO', 'Nrodistrito' => 4],
            ['id' => 901, 'nombre_urbanizacion' => 'RIO SECO SECTOR 25 DE JULIO', 'Nrodistrito' => 4],
            ['id' => 902, 'nombre_urbanizacion' => 'RIO  SECO BARRIO MUNICIPAL', 'Nrodistrito' => 4],
            ['id' => 903, 'nombre_urbanizacion' => 'JUANA AZURDUY  DE PADILLA U.V.A.', 'Nrodistrito' => 4],
            ['id' => 904, 'nombre_urbanizacion' => 'JUANA AZURDUY  DE PADILLA U.V.F.G.', 'Nrodistrito' => 4],
            ['id' => 905, 'nombre_urbanizacion' => 'JUANA AZURDUY  DE PADILLA U.V.B.', 'Nrodistrito' => 4],
            ['id' => 906, 'nombre_urbanizacion' => 'NUEVA JERUSALEN', 'Nrodistrito' => 4],
            ['id' => 907, 'nombre_urbanizacion' => '16 DE FEBRERO', 'Nrodistrito' => 4],
            ['id' => 908, 'nombre_urbanizacion' => 'ARTESANOS III - 27 DE MAYO', 'Nrodistrito' => 4],
            ['id' => 909, 'nombre_urbanizacion' => '2 DE FEBRERO ARTESANOS IV C', 'Nrodistrito' => 4],
            ['id' => 910, 'nombre_urbanizacion' => 'ARTESANOS IV A Y B', 'Nrodistrito' => 4],
            ['id' => 911, 'nombre_urbanizacion' => '24 DE SEPTIEMBRE', 'Nrodistrito' => 4],
            ['id' => 912, 'nombre_urbanizacion' => 'PLAN 9 DE ABRIL', 'Nrodistrito' => 4],
            ['id' => 913, 'nombre_urbanizacion' => 'AGUA DE LA VIDA', 'Nrodistrito' => 4],
            ['id' => 914, 'nombre_urbanizacion' => 'PLAN 194', 'Nrodistrito' => 4],
            ['id' => 915, 'nombre_urbanizacion' => 'PLAN 192', 'Nrodistrito' => 4],
            ['id' => 916, 'nombre_urbanizacion' => 'RIO SECO  (LOTES Y SERVICIOS)', 'Nrodistrito' => 4],
            ['id' => 917, 'nombre_urbanizacion' => '23 DE MARZO', 'Nrodistrito' => 4],
            ['id' => 918, 'nombre_urbanizacion' => 'PUERTA DEL SOL', 'Nrodistrito' => 4],
            ['id' => 919, 'nombre_urbanizacion' => 'VELEROS MINA CHOJLLA', 'Nrodistrito' => 4],
            ['id' => 920, 'nombre_urbanizacion' => 'COMPLEMENTO RIO SECO', 'Nrodistrito' => 4],
            ['id' => 921, 'nombre_urbanizacion' => 'RIO SECO COMPLEMENTO YUNGUYO II', 'Nrodistrito' => 4],
            ['id' => 922, 'nombre_urbanizacion' => 'VILLA ORIENTAL', 'Nrodistrito' => 4],
            ['id' => 923, 'nombre_urbanizacion' => 'LOTEO VILLA ORIENTAL', 'Nrodistrito' => 4],
            ['id' => 924, 'nombre_urbanizacion' => 'RIO SECO EXTRANCA', 'Nrodistrito' => 4],
            ['id' => 925, 'nombre_urbanizacion' => 'MERCEDARIO SECTOR 2  CALAMA', 'Nrodistrito' => 4],
            ['id' => 926, 'nombre_urbanizacion' => 'RIO SECO SECTOR LIBERTAD', 'Nrodistrito' => 4],
            ['id' => 927, 'nombre_urbanizacion' => 'SANTA BARBARA', 'Nrodistrito' => 4],
            ['id' => 928, 'nombre_urbanizacion' => 'SAN FELIPE DE SEQUE SECTOR 8', 'Nrodistrito' => 4],
            ['id' => 929, 'nombre_urbanizacion' => '1RO DE JUNIO YUNGUYO', 'Nrodistrito' => 4],
            ['id' => 930, 'nombre_urbanizacion' => 'COMPLEMENTO GRAN PODER', 'Nrodistrito' => 4],
            ['id' => 931, 'nombre_urbanizacion' => 'MERCEDARIO SEC. 8', 'Nrodistrito' => 4],
            ['id' => 932, 'nombre_urbanizacion' => 'MERCEDARIO SEC. 5-2', 'Nrodistrito' => 4],
            ['id' => 933, 'nombre_urbanizacion' => 'MERCEDARIO SEC. 7', 'Nrodistrito' => 4],
            ['id' => 934, 'nombre_urbanizacion' => 'MERCEDARIO SEC. 5-1', 'Nrodistrito' => 4],
            ['id' => 935, 'nombre_urbanizacion' => 'MERCEDARIO FONVIS', 'Nrodistrito' => 4],
            ['id' => 936, 'nombre_urbanizacion' => 'SAN FELIPE DE SEQUE', 'Nrodistrito' => 4],
            ['id' => 937, 'nombre_urbanizacion' => 'MERCEDARIO SECCION 4', 'Nrodistrito' => 4],
            ['id' => 938, 'nombre_urbanizacion' => 'MERCEDARIO', 'Nrodistrito' => 4],
            ['id' => 939, 'nombre_urbanizacion' => 'ANEXO VILLA TUNARI', 'Nrodistrito' => 4],
            ['id' => 940, 'nombre_urbanizacion' => 'MUNICIPAL ILLIMANI', 'Nrodistrito' => 4],
            ['id' => 941, 'nombre_urbanizacion' => 'COMPLEMENTO YUNGUYO', 'Nrodistrito' => 4],
            ['id' => 942, 'nombre_urbanizacion' => 'MERCEDARIO 1 MZNA 41 Y 42', 'Nrodistrito' => 4],
            ['id' => 943, 'nombre_urbanizacion' => 'LOTEO THUNKA', 'Nrodistrito' => 4],
            ['id' => 944, 'nombre_urbanizacion' => 'COMPLEMENTO NUEVA MARCA', 'Nrodistrito' => 4],
            ['id' => 945, 'nombre_urbanizacion' => '31 DE JUNIO', 'Nrodistrito' => 4],
            ['id' => 946, 'nombre_urbanizacion' => 'A.S.F.S. 10', 'Nrodistrito' => 4],
            ['id' => 947, 'nombre_urbanizacion' => 'EX SALVIETTI', 'Nrodistrito' => 4],
            ['id' => 948, 'nombre_urbanizacion' => 'RIO SECO DISTRITO INDUSTRIAL 10', 'Nrodistrito' => 4],
            ['id' => 949, 'nombre_urbanizacion' => 'SAN PEDRO DE YUNGUYO', 'Nrodistrito' => 4],
            ['id' => 950, 'nombre_urbanizacion' => 'EX HACIENDA SAN ROQUE', 'Nrodistrito' => 7],
            ['id' => 951, 'nombre_urbanizacion' => 'CAZAS', 'Nrodistrito' => 7],
            ['id' => 952, 'nombre_urbanizacion' => 'EUCALIPTUS', 'Nrodistrito' => 8],
            ['id' => 953, 'nombre_urbanizacion' => 'LOTEAMIENTO SAN ANDRES', 'Nrodistrito' => 14],
            ['id' => 954, 'nombre_urbanizacion' => 'COMPLEMENTO MEJILLONES', 'Nrodistrito' => 5],
            ['id' => 955, 'nombre_urbanizacion' => 'ANEXO VILLA ESPERANZA', 'Nrodistrito' => 5],
            ['id' => 956, 'nombre_urbanizacion' => 'ANEXO LAG 21 DE SEPTIEMBRE', 'Nrodistrito' => 7],
            ['id' => 957, 'nombre_urbanizacion' => 'RAMA', 'Nrodistrito' => 8],
            ['id' => 958, 'nombre_urbanizacion' => 'LOTEO 16 DE DICIEMBRE', 'Nrodistrito' => 7],
            ['id' => 959, 'nombre_urbanizacion' => '1RO DE MAYO', 'Nrodistrito' => 7],
            ['id' => 960, 'nombre_urbanizacion' => 'MIRAFLORES SAN ROQUE', 'Nrodistrito' => 7],
            ['id' => 961, 'nombre_urbanizacion' => '19 DE JUNIO', 'Nrodistrito' => 7],
            ['id' => 962, 'nombre_urbanizacion' => 'CHAIÑA', 'Nrodistrito' => 7],
            ['id' => 963, 'nombre_urbanizacion' => 'VILLA ALEJANDRA', 'Nrodistrito' => 8],
            ['id' => 964, 'nombre_urbanizacion' => 'MIRADOR 39', 'Nrodistrito' => 8],
            ['id' => 965, 'nombre_urbanizacion' => 'SAN JUAN ALTO CHIJINI', 'Nrodistrito' => 12],
            ['id' => 966, 'nombre_urbanizacion' => 'ESMERALDA MIL', 'Nrodistrito' => 7],
            ['id' => 967, 'nombre_urbanizacion' => 'LOTEO COMPLEMENTO 14 DE ENERO LAGUNA', 'Nrodistrito' => 7],
            ['id' => 968, 'nombre_urbanizacion' => 'LOS LIRIOS', 'Nrodistrito' => 7],
            ['id' => 969, 'nombre_urbanizacion' => 'ALTO CHIJINI UNIDAD VECINAL \"B\"', 'Nrodistrito' => 12],
            ['id' => 970, 'nombre_urbanizacion' => 'MALLKU DE LOS ANDES', 'Nrodistrito' => 12],
            ['id' => 971, 'nombre_urbanizacion' => 'ALONZO DE MENDOZA', 'Nrodistrito' => 8],
            ['id' => 972, 'nombre_urbanizacion' => 'SIN RIVAL', 'Nrodistrito' => 8],
            ['id' => 973, 'nombre_urbanizacion' => 'ALTO CHIJINI UNIDAD VECINAL  \"A\"', 'Nrodistrito' => 12],
            ['id' => 974, 'nombre_urbanizacion' => 'LOS ROSEDALES', 'Nrodistrito' => 8],
            ['id' => 975, 'nombre_urbanizacion' => 'COMPLEMENTO 12 DE ABRIL', 'Nrodistrito' => 8],
            ['id' => 976, 'nombre_urbanizacion' => 'SAN JOSE (ACHOCALLA)', 'Nrodistrito' => 8],
            ['id' => 977, 'nombre_urbanizacion' => 'SAN SIMON DE PAMPA GRANDE', 'Nrodistrito' => 8],
            ['id' => 978, 'nombre_urbanizacion' => 'JUNTU HUMA', 'Nrodistrito' => 8],
            ['id' => 979, 'nombre_urbanizacion' => 'VICTORIA \"II\"', 'Nrodistrito' => 8],
            ['id' => 980, 'nombre_urbanizacion' => 'UTASA II', 'Nrodistrito' => 8],
            ['id' => 981, 'nombre_urbanizacion' => 'UTASA', 'Nrodistrito' => 8],
            ['id' => 982, 'nombre_urbanizacion' => 'COPACABANA FONVIS', 'Nrodistrito' => 8],
            ['id' => 983, 'nombre_urbanizacion' => 'COPACABANA FONVIS SECTOR VII', 'Nrodistrito' => 8],
            ['id' => 984, 'nombre_urbanizacion' => 'VENTILLA PRIMERO', 'Nrodistrito' => 8],
            ['id' => 985, 'nombre_urbanizacion' => 'JUNTHUMA TARAPACA', 'Nrodistrito' => 8],
            ['id' => 986, 'nombre_urbanizacion' => 'LOTEO ANEXO 2 SENKATA 79', 'Nrodistrito' => 8],
            ['id' => 987, 'nombre_urbanizacion' => 'SAN MARCOS', 'Nrodistrito' => 8],
            ['id' => 988, 'nombre_urbanizacion' => 'SEÑOR DE VENTILLA', 'Nrodistrito' => 8],
            ['id' => 989, 'nombre_urbanizacion' => 'MIRAFLORES 1', 'Nrodistrito' => 8],
            ['id' => 990, 'nombre_urbanizacion' => 'LOTEAMIENTO ÑACAHUI PAMPA', 'Nrodistrito' => 8],
            ['id' => 991, 'nombre_urbanizacion' => 'ANEXO SENKATA 79', 'Nrodistrito' => 8],
            ['id' => 992, 'nombre_urbanizacion' => 'LOTEO MATILDE', 'Nrodistrito' => 14],
            ['id' => 993, 'nombre_urbanizacion' => 'LOTEO LAS RETAMAS II MILLUNI BAJO', 'Nrodistrito' => 14],
            ['id' => 994, 'nombre_urbanizacion' => 'LOTEO ANEXO RETAMAS', 'Nrodistrito' => 14],
            ['id' => 995, 'nombre_urbanizacion' => 'BONANZA 2014', 'Nrodistrito' => 14],
            ['id' => 996, 'nombre_urbanizacion' => 'LOTEO ASUNCION', 'Nrodistrito' => 13],
            ['id' => 997, 'nombre_urbanizacion' => 'ROSALINDA MILLUNI BAJO', 'Nrodistrito' => 14],
            ['id' => 998, 'nombre_urbanizacion' => 'ANEXO PALESTINA', 'Nrodistrito' => 14],
            ['id' => 999, 'nombre_urbanizacion' => '29 DE JUNIO LOTEAMIENTO', 'Nrodistrito' => 14],
            ['id' => 1000, 'nombre_urbanizacion' => 'HICHUSIRCA GRANDE SECTOR PATRIARCA', 'Nrodistrito' => 7],
            ['id' => 1002, 'nombre_urbanizacion' => 'OTRA UBICACION ESPECIFICADA EN OBSERVACIONES', 'Nrodistrito' => 15],
            ['id' => 1003, 'nombre_urbanizacion' => 'VILLA BOLIVAR \"D\"', 'Nrodistrito' => 3],
            ['id' => 1004, 'nombre_urbanizacion' => '6 DE JUNIO', 'Nrodistrito' => 3],
            ['id' => 1005, 'nombre_urbanizacion' => 'COLLPANI', 'Nrodistrito' => 3],
            ['id' => 1006, 'nombre_urbanizacion' => 'VILLA DOLORES', 'Nrodistrito' => 3],
            ['id' => 1007, 'nombre_urbanizacion' => 'ELIZARDO PEREZ', 'Nrodistrito' => 3],
            ['id' => 1008, 'nombre_urbanizacion' => '21 DE SEPTIEMBRE', 'Nrodistrito' => 1],
            ['id' => 1009, 'nombre_urbanizacion' => 'COPACABANA', 'Nrodistrito' => 1],
            ['id' => 1010, 'nombre_urbanizacion' => 'VILLA ALEMANIA', 'Nrodistrito' => 1],
            ['id' => 1011, 'nombre_urbanizacion' => 'VILLA BOLIVA \"C\"', 'Nrodistrito' => 1],
            ['id' => 1012, 'nombre_urbanizacion' => 'SANTIAGO 1RO', 'Nrodistrito' => 1],
            ['id' => 1013, 'nombre_urbanizacion' => 'ALPACOMA BAJO', 'Nrodistrito' => 1],
            ['id' => 1014, 'nombre_urbanizacion' => 'CHASQUIPAMPA', 'Nrodistrito' => 1],
            ['id' => 1015, 'nombre_urbanizacion' => 'ALTO CHIJINI', 'Nrodistrito' => 1],
            ['id' => 1016, 'nombre_urbanizacion' => 'TARAPACA JUNTUMI', 'Nrodistrito' => 1],
            ['id' => 1017, 'nombre_urbanizacion' => 'ALTO TACAGUA', 'Nrodistrito' => 1],

        ];
        foreach ($urb as $newurb) {
            $addurb = new urbanizacion();
            $addurb->id = $newurb['id'];  // Acceder correctamente al valor del array
            $addurb->Nrodistrito = $newurb['Nrodistrito'];
            $addurb->nombre_urbanizacion = $newurb['nombre_urbanizacion'];  // Asignar el valor directamente
            $addurb->save();  // Guardar el modelo
        }
    }
}
